#!/usr/bin/env node
/**
 * Batch translate all listing titles to Chinese.
 * Updates title_zh in all 3 raw collections + targeted_results.
 *
 * Usage: node src/scripts/translate-titles.js
 */

const { MongoClient } = require('mongodb');
const config = require('../config');
const logger = require('../lib/logger');

// ─── Translation Map (Gemini-translated, 489 unique titles) ──────

const TRANSLATIONS = {
  "Stunning Layout|Comfortable Living|Ideal Location": "极佳户型 | 舒适生活 | 黄金地段",
  "Contemporary Studio Apartment in a Creative Island Setting": "创意岛屿环境中的现代开间公寓",
  "AMAZING SEA VIEW WONDERFUL WATERFRONT LOCALITY": "迷人海景 绝佳滨水地段",
  "Upcoming | Modern Layout | Mangrove Views": "即将推出 | 现代布局 | 红树林景观",
  "Furnished Studio | Open View | Ready To Move": "带家具开间 | 开阔视野 | 即可入住",
  "New Luxurious Studio | Sea View +Balcony |": "全新豪华开间 | 海景 + 阳台",
  "Brand New Studio W/ Swimming Pool & Gym I Parking": "全新开间 附带泳池 & 健身房 及停车位",
  "Furnished Studio | Pool View | Urban Lifestyle": "带家具开间 | 泳池景观 | 都市生活方式",
  "⁂Fully Furnished⁂Flexible Payments⁂Ready To Move⁂": "⁂家具齐全⁂灵活付款⁂即可入住⁂",
  "A Perfect Studio Unit Just for You with Facilities": "为您量身打造的完美开间 设施齐全",
  "Upcoming | Studio apartment in Masdar Oasis": "即将推出 | Masdar Oasis 的开间公寓",
  "Elegant Studio| Fully furnished |Ready to move": "优雅开间 | 家具齐全 | 即可入住",
  "unfurnished 60k Studio Apartment furnished 70k With Private Balcony | American Style Kitchen | Share Pool + Gym": "不带家具 60k 开间公寓 带家具 70k 附带私人阳台 | 美式厨房 | 公用泳池 + 健身房",
  "High Floor Studio Fully Furnished | Ready to Move": "高层开间 家具齐全 | 即可入住",
  "Partial Canal View Lavish Layout Great Amenities": "侧面运河景 奢华布局 优质设施",
  "Partial Canal View | Spacious Studio | Vacant": "侧面运河景 | 宽敞开间 | 空置",
  "Furnished Studio with balcony In Al khalidiyah , Zayed the first street/ 6200 Monthly": "带家具及阳台开间 位于 Al khalidiyah, Zayed the first street / 每月 6200",
  "Elegant Studio | Amazing Facilities | Luxury Living": "优雅开间 | 顶级设施 | 奢华生活",
  "Water View | Ready To Move | Flexible Payments": "水景房 | 即可入住 | 灵活付款",
  "Fully Furnished | Studio | Ready to move in": "家具齐全 | 开间 | 即可入住",
  "Book Today Partial Sea View Ready To Move": "今日预订 侧面海景 即可入住",
  "High Floor Partial Sea View Ready To Move In": "高层侧面海景 即可入住",
  "Fully Furnished Studio | Modern Design": "精装修开间 | 现代设计",
  "VACANT | Urban View | Upto 4 Payments | High Floor": "空置 | 都市景观 | 最多4期付款 | 高层",
  "Limited Offer | Vacant | 1 Payment": "限时优惠 | 空置 | 1期付款",
  "Mangrove View | Big Kitchen | Spacious Studio": "红树林景观 | 大厨房 | 宽敞开间",
  "HOT OFFER!! FULLY FURNISHED - STUDIO | PRIME LOCATION | TOP NOTCH FACILITIES | 1 PAYMENT! | CALL US NOW!": "特惠房源！！家具齐全 - 开间 | 黄金地段 | 顶级设施 | 1期付款！| 立即致电！",
  "Ideal Studio | Full Facilities | Vacant": "理想开间 | 设施完善 | 空置",
  "Hot Deal | Vacant | Canal View | 1 Payment": "特惠房源 | 空置 | 运河景 | 1期付款",
  "Hot Deal | Ready To Move In | Prime Spot": "特惠房源 | 即可入住 | 黄金地段",
  "Fully Furnished | Prime Area | Ready To Move": "家具齐全 | 黄金地段 | 即可入住",
  "Spacious Layout | Prime Location | Move in Ready": "宽敞布局 | 黄金地段 | 即可入住",
  "Ready to Move | 12 Payments 78K | Mangrove View": "即可入住 | 12期付款 78K | 红树林景观",
  "Best Priced Studio Fully Furnished Home | Book Now": "性价比最高带家具开间 | 立即预订",
  "Ready To Move In Partial Sea View Prime Location": "即可入住 侧面海景 黄金地段",
  "Upcoming| Elegant Unit| Mangrove Views|Prime Area": "即将推出 | 优雅单元 | 红树林景观 | 黄金地段",
  "Vacant | Fully Furnished Studio | Best Facilities": "空置 | 精装修开间 | 顶级设施",
  "HOT DEAL! Community View | Mid Level": "特惠！社区景观 | 中层",
  "Extra-Spacious Living | Hot Deal | Move-In Ready": "超宽敞居住空间 | 特惠 | 即可入住",
  "Ready Unit | Near NYU | Chiller Free": "现房 | 靠近 NYU | 免空调费",
  "Ready To Move In | Mangrove View | Layout 03": "即可入住 | 红树林景观 | 03户型",
  "Fully Furnished | Flexible Payment | Ready to Move": "家具齐全 | 灵活付款 | 即可入住",
  "Super Hot Deal | Spacious Studio + Parking": "超级特惠 | 宽敞开间 + 停车位",
  "Fully furniture / Vacant / High floor": "家具齐全 / 空置 / 高层",
  "Available Soon! Sea View | Higher Level": "即将上市！海景 | 高层",
  "Spacious Studio | Fully Furnished | Flexible Payment": "宽敞开间 | 家具齐全 | 灵活付款",
  "Ready Studio | The Gate, Al Reem | 5 Cheques": "开间现房 | Al Reem, The Gate | 5张支票付清",
  "Ready to move in Furnished studio apartment In Al Falah Street, / 6.2 k Monthly": "即可入住带家具开间公寓 位于 Al Falah Street / 每月 6.2 k",
  "Vacant | Elegant Studio | Furnished | Scenic View": "空置 | 优雅开间 | 带家具 | 景观美房",
  "Top Amenities | Studio W Balcony | Fully Furnished |": "顶级配套 | 带阳台开间 | 家具齐全",
  "Cozy Studio | Relaxing Partial Sea View | Vacant": "温馨开间 | 惬意侧面海景 | 空置",
  "Pristine Condition | Move in Ready | Prime Location": "状态极佳 | 即可入住 | 黄金地段",
  "Balcony | Modern Layout | Canal View": "阳台 | 现代布局 | 运河景",
  "Ground Floor | Ready To Move | Luxury Lifestyle": "底层 | 即可入住 | 奢华生活方式",
  "Book Now Ferrari World View With Flexible Payments": "立即预订 Ferrari World 景观 灵活付款",
  "Modern Studio | Perfect Living | Great Location": "现代开间 | 完美生活 | 绝佳地段",
  "Sold us Unfurnished | Cozy Layout | Spacious Home": "不带家具出租 | 温馨布局 | 宽敞家园",
  "GET THE DEAL AMAZING LOCATION MOVE NOW HOT PRICE": "抢购特惠 绝佳地段 立即入住 热门价格",
  "Ground Floor | Community View | 2 Payments": "底层 | 社区景观 | 2期付款",
  "Cozy Fully Furnished | Vacant | Great Amenities": "温馨家具齐全 | 空置 | 优质设施",
  "A Fully Furnished Home | Biggest Layout | Book Now": "家具齐全家园 | 最大户型 | 立即预订",
  "Prime Studio | Vacant Now | Stunning Views": "优质开间 | 现已空置 | 迷人景观",
  "Furnished Studio | Mangrove View | Prime Location": "带家具开间 | 红树林景观 | 黄金地段",
  "Ready to Move | Fully Furnished | Flexible Payment": "即可入住 | 家具齐全 | 灵活付款",
  "Huge & Bright | Ready To Move | Stunning Views | Modern Finishing": "宽敞明亮 | 即可入住 | 迷人景观 | 现代装修",
  "Semi Furnished Studio | Single Payment | Vacant": "部分家具开间 | 一次性付款 | 空置",
  "Mangrove View | Well Maintained | Furnished Apt": "红树林景观 | 维护良好 | 带家具公寓",
  "Prime Location | Ground Floor | Upcoming | Book it": "黄金地段 | 底层 | 即将推出 | 立即预订",
  "Fully Furnished Studio | Mangrove View | High Floor": "精装修开间 | 红树林景观 | 高层",
  "Mangrove View | Big Kitchen | Ready To Move": "红树林景观 | 大厨房 | 即可入住",
  "Balcony | Fully Furnished | Prime Location": "阳台 | 家具齐全 | 黄金地段",
  "Up Coming | City &Mangrove view | Flexible Payment": "即将推出 | 城市 & 红树林景观 | 灵活付款",
  "Cozy Studio | Mangrove View | Vacant": "温馨开间 | 红树林景观 | 空置",
  "Ground Floor | Ferrari View | UPCOMING!": "底层 | Ferrari 景观 | 即将推出！",
  "Cozy Studio | Partly Furnished | Ready to Move": "温馨开间 | 部分家具 | 即可入住",
  "Spacious Studio | Modern Urban Living | Book Now": "宽敞开间 | 现代都市生活 | 立即预订",
  "Balcony | Ferrari World View | Upcoming Feb 14": "阳台 | Ferrari World 景观 | 2月14日可用",
  "Fully Furnished | Mangrove View | High Floor": "精装修 | Mangrove 景观 | 高层",
  "Mangrove and City View| Spacious| Ready To Move In": "Mangrove 及城市景观 | 宽敞 | 即可入住",
  "⁂ Sea View ⁂ Prime Area ⁂ Big Kitchen ⁂": "⁂ 海景 ⁂ 黄金地段 ⁂ 大厨房 ⁂",
  "Modern Studio Apartment | The Bridges, Reem Island | Direct Owner": "现代开间 | Reem Island, The Bridges | 业主直租",
  "Luxury Studio | Amazing View | Flexible Payment": "豪华开间 | 绝佳景观 | 灵活支付",
  "Vacant|Fully-Furnished|Vibrant Living| Prime Area": "空置 | 精装修 | 活力生活 | 黄金地段",
  "Stunning Studio | Beautiful View | Prime location": "精美开间 | 优美景观 | 黄金地段",
  "Spacious Studio| Mangrove View|Over 3 Installments": "宽敞开间 | Mangrove 景观 | 可分3期支付",
  "Furnished Studio | City View | Best price": "带家具开间 | 城市景观 | 超值价格",
  "Luxury Living Elegant Studio | Amazing Facilities |": "豪华生活 优雅开间 | 完善设施",
  "Ready To Move | Fully Furnished | Huge & Bright": "即可入住 | 精装修 | 宽敞明亮",
  "Cozy Studio | Mangrove View | Upcoming Unit | Monthly Cheques": "温馨开间 | Mangrove 景观 | 即将推出 | 按月支付",
  "Luxury Studio with Amazing View | Available | Flexible Payment": "豪华开间 绝佳景观 | 现房 | 灵活支付",
  "Fully Furnished | Upcoming | Book Now": "精装修 | 即将推出 | 立即预订",
  "Ready to move l High Floor | Balcony | Sea View": "即可入住 | 高层 | 阳台 | 海景",
  "√High Floor | Up to 2 Payments | Community View√": "√高层 | 最多2期支付 | 社区景观√",
  "Brand New Studio Apartment | The Gate Masdar City": "全新开间 | The Gate Masdar City",
  "Ideal Studio for Professionals | Mangrove Views | VACANT": "商务人士理想开间 | Mangrove 景观 | 空置",
  "Ideal for Urban Living | Vacant | Book Now": "都市生活理想之选 | 空置 | 立即预订",
  "Fully Furnished Studio with balcony In Al khalidiyah , Zayed the first street, / 5900 Monthly": "Al khalidiyah, Zayed the first street 精装带阳台开间 / 月租 5900",
  "Modern Studio | Amazing Facilities | Prime Location": "现代开间 | 完善设施 | 黄金地段",
  "Open-Plan Studio | Balcony | Prime Location": "开放式格局开间 | 阳台 | 黄金地段",
  "Spacious Studio | Mangrove View | Ready to Move": "宽敞开间 | Mangrove 景观 | 即可入住",
  "Hot Deal | Spacious Studio | Ready to Move | Amazing Balcony": "特价房 | 宽敞开间 | 即可入住 | 景观阳台",
  "Ready To Move In | Perfect Home | Prime Area": "即可入住 | 理想之家 | 黄金地段",
  "Open Layout Studio | Balcony | Premium Location": "开放式布局开间 | 阳台 | 优越地段",
  "VACANT / SEA VIEW / SIX PAYMENTS": "空置 / 海景 / 六次支付",
  "Exclusive with Us | Prime Location | Ready to Move": "独家房源 | 黄金地段 | 即可入住",
  "Spacious Layout | Mangrove View | Ready to Move": "宽敞格局 | Mangrove 景观 | 即可入住",
  "Modern Studio | Furnished | Ready to Move": "现代开间 | 带家具 | 即可入住",
  "Furnished Unit| Well Maintained| Ready To Move": "精装单元 | 维护良好 | 即可入住",
  "Well Organized Studio| Partial Sea View| Vacant": "格局合理开间 | 部分海景 | 空置",
  "Hot Deal | Studio | Pool+ Gym | Ready To Move |": "特价 | 开间 | 泳池+健身房 | 即可入住",
  "Stunning Studio | Modern Living | Ready To Move": "精美开间 | 现代生活 | 即可入住",
  "Spacious Layout | Modern Home | Prime Location": "宽敞格局 | 现代住宅 | 黄金地段",
  "Balcony | High Floor | Ready To Move": "阳台 | 高层 | 即可入住",
  "Elegant Studio | Amazing Layout | Enquire Now!": "优雅开间 | 绝佳布局 | 立即咨询！",
  "Full Canal View | Fully Furnished | Modern Layout": "全运河景观 | 精装修 | 现代格局",
  "Open View | Best Investment | Spacious Studio": "视野开阔 | 最佳投资 | 宽敞开间",
  "HOT Deal | Canal View | Cozy Balcony | Book Now !": "特价房 | 运河景观 | 温馨阳台 | 立即预订！",
  "Great Deal | ST w/ Balcony | Ready to Move": "超值优惠 | 带阳台开间 | 即可入住",
  "Fully Furnished With Appliances | Monthly Payment": "精装修含家电 | 按月支付",
  "Ready Studio| Near NYUAD | Chiller Free": "精装开间 | 靠近 NYUAD | 免空调费",
  "Ready To Move Fully Furnished | Magnificent Studio": "即可入住精装修 | 豪华开间",
  "Big 1BR Groud Floor | Affordable and Flexible Payment": "宽敞一居室一楼 | 价格实惠 灵活支付",
  "Ready Soon | Spacious 1BR | Well-Planned Community": "即将完工 | 宽敞一居室 | 规划良好的社区",
  "Elegant And Spacious 1BHK With Separate Kitchen, Nice Washroom And Big Window In Khalifa City A": "Khalifa City A 优雅宽敞一居室，带独立厨房、精美卫浴和大窗户",
  "Tremendous 1BHK With Spacious Saloon & Closed Kitchen": "超大一居室，带宽敞客厅和封闭式厨房",
  "Splendid 1 Master Bedroom With Balcony & Closed Kitchen": "精美一房主卧，带阳台和封闭式厨房",
  "Unfurnished Price! 1Bedroom With Water & Electricity Included": "毛坯价！一居室包水电",
  "Brand new-Modern spacious 1/BHK | Sep. kitchen | Modern bath | Parking": "全新现代宽敞一居室 | 独立厨房 | 现代卫浴 | 停车位",
  "Unfurnished 1 Bedroom Apartment With Parking & Water And Electricity Included": "未装修一居室公寓，带车位包水电",
  "Splendid 1BHK With Closed Kitchen & Spacious Saloon": "精美一居室，带封闭式厨房和宽敞客厅",
  "Splendid 1 Bedroom with 1 Bathroom With Balcony In Muroor Road Abu Dhabi.": "Abu Dhabi Muroor Road 精美一房一卫带阳台",
  "Stylish 1 BHK | Free ADDC | No Commission": "时尚一居室 | 包 ADDC 水电 | 无中介费",
  "Fully Renovated 1BHK Apartment with Balcony!!!": "全新翻修一居室公寓带阳台！！！",
  "EXCLUSIVE 1BHK PROPER APARTMENT AVAILABLE IN SHABIYA 09 (ASIANS ONLY)": "SHABIYA 09 独家优质一居室（仅限亚洲人）",
  "Splendid 1BHK With Balcony & Built-In Cupboards": "精美一居室，带阳台和嵌入式衣柜",
  "Deluxe 1BHK W/Balcony | Free ADDC | 0% Commission": "豪华一居室带阳台 | 包 ADDC 水电 | 零中介费",
  "Brand New 1Bhk Apt With 2 Bathroom Big Kitchen": "全新一居室公寓，双卫大厨房",
  "Deluxe 1BHK | Free ADDC | NO COMMISSION | Just Listed": "豪华一居室 | 包 ADDC 水电 | 无中介费 | 最新上市",
  "Specious 1BHK in Mushrif Area | Free ADDC | 0% Commission": "Mushrif Area 宽敞一居室 | 包 ADDC 水电 | 零中介费",
  "Charming 1BHK | No Commission | Free Water And Electricity": "迷人一居室 | 无中介费 | 包水电",
  "1-BHK Flat with balcony": "带阳台的一居室公寓",
  "1 BHK Apartment in Al Nahyan – AED 65,000 | 4 Payments": "Al Nahyan 一居室公寓 – 65,000 迪拉姆 | 可分4期支付",
  "⇛ Prime Area ⇛ Spacious Unit ⇛ Ready To Move ⇚": "⇛ 黄金地段 ⇛ 宽敞单元 ⇛ 即可入住 ⇚",
  "Hot deal | Good location | Good price": "特价房 | 位置优越 | 价格优惠",
  "PREMIUM DEAL! Fully Furnished | Big Balcony | 1 Parking | 1 Payment": "优质房源！精装修 | 大阳台 | 1个停车位 | 一次性支付",
  "VACANT HOT DEAL 1PAY 1BR APT TYPE H READY TO MOVE": "空置特价 一次性支付 H型一居室 即可入住",
  "Spacious 1BHK | with Balcony & Laundry Room": "宽敞一居室 | 带阳台和洗衣房",
  "Modern 1 BHK with a perfect balance of space & style": "现代一居室，空间与风格的完美平衡",
  "1BR Urban Living | Prime Setting | Ready to Move": "一居室都市生活 | 黄金地段 | 即可入住",
  "COOL COMMUNITY AMAZING FACILITIES NEAR DUBAI": "绝佳社区 完善设施 靠近 Dubai",
  "LUXURY 1BHK !! SHARED POOL !! SEP KITCHEN !! PROPER WASHROOM !! KCA": "豪华一居室！！共享泳池！！独立厨房！！独立卫浴！！KCA",
  "Deluxe 1 BHK W/ 0% Commission Free ADDC | Hot Deal": "豪华一居室 零中介费 包 ADDC 水电 | 特价房",
  "Elegant Upcoming 1 BR Apartment Street & Mall view": "优雅即将上市一居室，街景及商场景观",
  "High Quality Living | 1-Bedroom Apartment with Balcony & Premium Amenities for AED 80,000 Only. !": "高品质生活 | 带阳台一居室，配备高端设施，仅需 80,000 迪拉姆！",
  "American Style Very Big 1Bedroom+ Kitchen+ separate Washroom": "美式风格超大一居室 + 厨房 + 独立卫生间",
  "Elegant Living | Amazing View | Unfurnished": "优雅生活 | 绝佳视野 | 不带家具",
  "1bhk Available Near WTC Water electricity included": "WTC 附近一居室，包水电",
  "Loft 1BR Layout | Balcony | Ready to move in soon": "复式一居室布局 | 带阳台 | 即将可拎包入住",
  "1bhk Available Big Size Nice View Nice Area": "大户型一居室，视野开阔，地段优越",
  "G Floor l Ready To Move In l Near Swimming Pool": "底层 | 随时入住 | 靠近游泳池",
  "Chic 1BR | Sustainable Living | Great Value": "别致一居室 | 可持续生活 | 超值之选",
  "Available Soon I From Owner I Prime Location": "即将空置 | 房东直租 | 黄金地段",
  "Vacant / Ready to move / Balcony": "空置 / 随时入住 / 带阳台",
  "Apartment for Rent in Al Danah – Abu Dhabii - 75,000/year": "Al Danah – Abu Dhabi 公寓出租 - 75,000/年",
  "Furnished 1BR | Ground Level | Modern Living": "带家具一居室 | 一楼 | 现代生活",
  "Up-Coming 1BHK | Driect Owner | No Agent Fee | No Bills": "即将上市一居室 | 房东直租 | 免中介费 | 包杂费",
  "Vacant soon / Mangrove view / Great Facilities": "即将空置 / 红树林景观 / 设施齐全",
  "Well Maintained | Move In Ready | Low Floor": "维护良好 | 随时入住 | 低楼层",
  "Hot Deal! Loft-Type Unit Near the Pool | Upcoming": "特惠！靠近泳池的复式单元 | 即将上市",
  "Ready to move | Modern | Spacious 1BDR": "随时入住 | 现代风格 | 宽敞一居室",
  "RTM II Prime Location II 0% Commission II Tawtheeq Available": "随时入住 | 黄金地段 | 0 中介费 | 可办 Tawtheeq",
  "Spacious Furnished One Bedroom Apartment In Al Danah, Al Falah Street / 7.6k Monthly": "Al Danah, Al Falah Street 宽敞带家具一居室 / 月租 7,600",
  "Investor Deal | Loft type | Ground Floor": "投资首选 | 复式户型 | 一楼",
  "Charming 1 Bedroom Hall Apartment With 2 Bathrooms Nearby Electra Park": "Electra Park 附近迷人一室一厅，带两个卫生间",
  "Charming 1 BR Junior | Elegant Community": "迷人精致一居室 | 优雅社区",
  "Prime Location/ Ready To Move/ Tawtheeq Available/ No Commission": "黄金地段 / 随时入住 / 可办 Tawtheeq / 免中介费",
  "1BR with Good Facilities | Serene Community": "设施完善一居室 | 宁静社区",
  "READY TO MOVE | 1BR APARTMENT W/BALCONY | FAMILY COMMUNITY": "随时入住 | 带阳台一居室 | 家庭社区",
  "Stunning One Bedroom Apartment In a Tourist Club Area / Monthly 7k/-AED": "Tourist Club Area 绝美一居室 / 月租 7,000 迪拉姆",
  "Available Now | 1 Bedroom | New Building | Ready To Move": "现房 | 一居室 | 新楼 | 随时入住",
  "Limited Offer | Modernistic Apartment | Basement Parking | Ready to Move": "限时优惠 | 现代风格公寓 | 地下停车位 | 随时入住",
  "Furnished | Canal View | Move-In Ready": "带家具 | 运河景观 | 随时入住",
  "Limited-Time Offer | Beautifully Designed | Utilities Free | Great Location | Book Today": "限时优惠 | 设计精美 | 免水电费 | 黄金地段 | 立即预订",
  "6400/month amazing finishing fully furnished 1 B/R hall with proper kitchen and bathtub": "月租 6,400，精装修带全套家具一室一厅，配标准厨房和浴缸",
  "Fully Furnished One Bedroom Apartment In Mamoura Area Near To Wahda Mall, Abu Dhabi. 7.5 k Monthly": "Abu Dhabi, Mamoura 地区靠近 Wahda Mall，全家具一居室，月租 7,500",
  "Furnished One Bedroom Apartment In Al Nahyan / Mamoura, Abu Dhabi 7.5 k Monthly": "Abu Dhabi, Al Nahyan / Mamoura 带家具一居室，月租 7,500",
  "1BHK 2 Bathrooms Apartment For Rent - Spacious Size": "宽敞一室二卫公寓出租",
  "Prime Location 1BR Apartment | Bawabat Al Sharq Mall, Baniyas": "黄金地段一居室 | Bawabat Al Sharq Mall, Baniyas",
  "Available on Monthly Basis | Furnished Apartment | Close to Wahda Mall": "可月租 | 带家具公寓 | 靠近 Wahda Mall",
  "Well-Planned 1-Bedroom Home in a Self-Sufficient Community": "自给自足社区内规划合理的一居室",
  "Cozy Unit in a Vibrant Residential Hub": "活力社区内的温馨单元",
  "1 BHK fully furnished apartment with all utilities included": "全家具一居室，包所有杂费",
  "Ready To Move ! Stunning Layout ! Inquire Now": "随时入住！绝佳户型！立即咨询",
  "Beautifully Designed Homes | Ready to Move In": "设计精美的住宅 | 随时入住",
  "Contemporary Design | Ready to Move | Enquire Now": "现代设计 | 随时入住 | 立即咨询",
  "Amazing 1BHK Apartment for Rent | Balcony | Central AC | Muroor Area, Abu Dhabi": "Abu Dhabi, Muroor Area 绝佳一居室出租 | 带阳台 | 中央空调",
  "Ready To Move In | Huge Balcony | Peaceful Living": "随时入住 | 超大阳台 | 宁静生活",
  "Alluring 1BHK With Closed Kitchen & Spacious Saloon": "迷人一居室，带封闭式厨房和宽敞客厅",
  "Newly Renovated One Bedroom | No Commission | Free ADDC": "新装修一居室 | 免中介费 | 免 ADDC 水电费",
  "Upcoming One-Bedroom II Prime Location II 0% Commission II Tawtheeq Available": "即将上市一居室 | 黄金地段 | 0 中介费 | 可办 Tawtheeq",
  "UPCOMING!! 1 BHK | GYM & POOL | JACUZZI | SAUNA | STEAM ROOM | TOP NOTCH FACILITIES | CALL US NOW!": "即将上市！！一居室 | 健身房与泳池 | 按摩浴缸 | 桑拿 | 蒸汽室 | 顶尖设施 | 立即致电！",
  "A Premium Residence | Full Facilities | Book Now!": "高端住宅 | 设施齐全 | 立即预订！",
  "Amazing 1bhk with balcony | Central AC | Al Najda Street-Abudhabi": "Al Najda Street-Abudhabi 绝佳带阳台一居室 | 中央空调",
  "READY TO MOVE IN • FLEXIBLE PAYMENTS • BEST OFFER!!": "随时入住 • 付款方式灵活 • 最优报价！！",
  "Super Delux Fully Furnished One Bedroom Apartment In Maourah, / 7.5 K Monthly": "Maourah 超豪华全家具一居室 / 月租 7,500",
  "Hot Offer | 1 Bedroom Apt | Facilities | Parking": "热门优惠 | 一居室公寓 | 设施完善 | 带车位",
  "SPACIOUS 1 BED | 4 PAYMENTS | GYM POOL | NO PARKING": "宽敞一居室 | 分 4 期付款 | 健身房泳池 | 无车位",
  "Spacious 1 Bedroom Apt | Facilities | Parking": "宽敞一居室公寓 | 设施完善 | 带车位",
  "Super Deluxe Fully Furnished One Bedroom Apartment Al Falah Street, / 7.5 K Monthly": "Al Falah Street 超豪华全家具一居室 / 月租 7,500",
  "Up-Coming || Prime Location || 0%commission || Tawtheeq Available||": "即将上市 || 黄金地段 || 0 中介费 || 可办 Tawtheeq ||",
  "Spectacular 1 Bedroom 0 Commission 0 Bills Tawtheeq Available": "绝佳一居室，0 中介费，包杂费，可办 Tawtheeq",
  "Elegant 1 Bedroom Tawtheeq Available 0 Commission Free Bills": "优雅一居室，可办 Tawtheeq，0 中介费，包杂费",
  "1BR+Store Room | Mangrove View | 1 Payment": "一居室 + 储藏室 | 红树林景观 | 一次性付清",
  "Limited offer |1 bedroom Apt | Facilities | Parking": "限时优惠 | 一居室公寓 | 设施完善 | 带车位",
  "1st Floor l Hot Deal l Spacious 1BR": "二楼 | 特惠 | 宽敞一居室",
  "Cozy Unit | Low Floor | Available": "温馨单元 | 低楼层 | 现房",
  "Available Soon | Best Amenities | Direct Owner | Tawtheeq": "即将空置 | 顶尖设施 | 房东直租 | 可办 Tawtheeq",
  "High Floor | Pool View | Flexible Payment | Junior": "高楼层 | 泳池景观 | 灵活付款 | 精致户型",
  "1st Floor l Upcoming l Book Now": "二楼 | 即将上市 | 立即预订",
  "Upcoming Deluxe 1 Bedroom Tawtheeq Available 0 Commission 0 Bills": "即将上市豪华一居室，可办 Tawtheeq，0 中介费，包杂费",
  "G Floor l Ready To Move In l Call Now": "底层 | 随时入住 | 立即致电",
  "Modern Living | Lower Level | Vacant": "现代生活 | 低楼层 | 空置",
  "PRIME LOCTION | RADY TO MOVE | HOT OFFER": "黄金地段 | 随时入住 | 热门优惠",
  "Prime Location l Peaceful Living l Spacious 1BR": "黄金地段 | 宁静生活 | 宽敞一居室",
  "Modern 1BHK for Rent | Vacant | First Floor": "现代一居室出租 | 空置 | 二楼",
  "Precious 1BR with Balcony | Type D | Available Soon": "精选带阳台一居室 | D 户型 | 即将空置",
  "Fully Furnished 1BR Apt in Vista, Al Maryah": "Al Maryah, Vista 全家具一居室公寓",
  "Spacious 1BR | Vacant Unit | Prime Location": "宽敞一居室 | 空置房源 | 黄金地段",
  "Ready to Move | 1BR | Fully Furnished |": "即可入住 | 一居室 | 家具齐全",
  "Ready To Move In l Great Price l Prime Location": "即可入住 | 价格优美 | 黄金地段",
  "Prime Community | Cozy Living | Ideal Amenities !": "优质社区 | 温馨居住 | 设施完善",
  "HUGE AND GOOD OFFER! 1BHK | CENTRAL AC | HUGE HALL | 3 PAYMENTS! | CALL US NOW!": "超值特惠！一室一厅 | 中央空调 | 超大客厅 | 可3次付款！| 立即咨询！",
  "Hot Deal! 1BR Apartment for RENT just 75K.": "热门房源！一居室公寓出租，仅需 7.5万",
  "Amazing Brand New 1Bhk In Al khalidiyah / 8199 Dhs Monthly Rent": "Al Khalidiyah 全新精美一室一厅 / 月租 8199 迪拉姆",
  "1BR Apartment | Mid Floor | Good Community": "一居室公寓 | 中楼层 | 优质社区",
  "1BHK Available Now for Rent ! City View | Book Now": "一室一厅即刻出租！城景房 | 立即预订",
  "Balcony | Ready to Move | Prime Location": "带阳台 | 即可入住 | 黄金地段",
  "Fully Furnished | First Floor | Well Maintain": "家具齐全 | 一楼 | 保养良好",
  "Flexible Payment 1BR with Balcony | First Floor | Available": "灵活付款，带阳台一居室 | 一楼 | 待租",
  "Balcony | Prime Location | Ready to Move": "带阳台 | 黄金地段 | 即可入住",
  "\"Create Your Oasis in the City – Luxurious and Modern 1BHK Apartment in Abu Dhabi!\"": "打造您的城市绿洲 – Abu Dhabi 豪华现代一室一厅公寓！",
  "Hot Deal ! Ready To Move | Modern Living": "超值特惠！即可入住 | 现代生活",
  "Ready To Move In l Prime Location l Great Deal": "即可入住 | 黄金地段 | 超值价格",
  "Specious 1 Bedroom Apartment for Families Near to Mushrif Mall": "Mushrif Mall 附近宽敞一居室，适合家庭居住",
  "Prime Location l Great Deal l Spacious 1BR": "黄金地段 | 超值房源 | 宽敞一居室",
  "Brand New 1 BHK W/2 Baths Zero Commission": "全新一室一厅双卫，免中介费",
  "Hot Offer | Spacious 1 Bedroom Apartment | Al Mamoura, Abu Dhabi": "热门优惠 | 宽敞一居室 | Abu Dhabi, Al Mamoura",
  "Modern home Great Layout 1 BHK Furnished Apartment": "现代家居，格局优越，家具齐全一室一厅",
  "Fully Furnished 1 Bedroom Apartment for Rent in Abu Dhabi City | All Bills Included | Prime Central Location": "Abu Dhabi 市中心家具齐全一居室出租 | 包水电网 | 核心地段",
  "Stunning !! 01bhk furnished apartment With balcony close to etihad plaza": "精美房源！Etihad Plaza 附近带阳台精装修一室一厅",
  "FULLY FURNISHED!! Studio Apartment With Closed Kitchen & Built-In Cupboards": "家具齐全！带独立厨房和内嵌式衣柜的单身公寓",
  "Effortless comfort, ready for your arrival | Flexible Stay | Fully Furnished": "极致舒适，拎包入住 | 租期灵活 | 家具齐全",
  "SPACIOUS 1 BED | 4 PAYMENTS | POOL PARKING | UPCOMING": "宽敞一居室 | 4次付款 | 带泳池车位 | 即将上线",
  "Stylish & Modern Studio Apartment In Zafaranah/ Monthly 6499/-AED": "Zafaranah 时尚现代单身公寓 / 月租 6499 迪拉姆",
  "Hot Deal |Elite Studio |Balcony Views|Prime Area": "热门房源 | 精英单身公寓 | 阳台景观 | 核心区域",
  "Fully Renovated| Upgraded Kitchen| Upgraded Bathroom|": "精装修 | 升级厨房 | 升级卫浴",
  "Distinctive Studio Apartment For Rent | Large Private Balcony | Spacious Area": "特色单身公寓出租 | 超大私家阳台 | 空间宽敞",
  "SPACIOUS | READY TO MOVE | WELL MAINTAINED": "空间宽敞 | 即可入住 | 保养良好",
  "Hot Deal! Hydra Studio | Furnished | Vacant | 65K": "热门特惠！Hydra 单身公寓 | 带家具 | 空置 | 6.5万",
  "Vacant | Ready to move in | Comfort Living": "空置 | 即可入住 | 舒适生活",
  "Modern Studio | Great Location | Peaceful Living": "现代单身公寓 | 地理位置优越 | 环境宁静",
  "Up-Coming | Prime Location | 0%commission | Tawtheeq Available": "即将上线 | 黄金地段 | 免佣金 | 可办 Tawtheeq",
  "Up - Coming Separate Entrance Studio | No Utilities | From Owner | No Agent Fee": "即将上线，独立入口单身公寓 | 不包水电 | 房东直租 | 免中介费",
  "Modern Studio | Big Layout | Ready to move in": "现代单身公寓 | 户型方正宽敞 | 即可入住",
  "Vacant Now | Studio | Parking | Gym | Pool": "现房空置 | 单身公寓 | 含车位 | 健身房 | 游泳池",
  "Community View| Spacious Studio| Ready To Move In": "社区景观 | 宽敞单身公寓 | 即可入住",
  "Amazing Studio in a Muroor / Monthly 4600/-AED": "Muroor 精美单身公寓 / 月租 4600 迪拉姆",
  "Smart Fully Furnished Studio Apartment In Al Khalidiyah Near to Etisalat Tower, Abu Dhabi 5500 AED Monthly": "Abu Dhabi, Al Khalidiyah (Etisalat Tower 附近) 智能精装单身公寓，月租 5500 迪拉姆",
  "Studio With Big Windows |Sep kitchen+Bathroom|KCA": "KCA 大窗单身公寓 | 独立厨卫",
  "Studio Ready to move Bawabat Al Sharq": "Bawabat Al Sharq 即可入住单身公寓",
  "Terrace | Upcoming 15th Mar | Spacious Studio": "带露台 | 3月15日上线 | 宽敞单身公寓",
  "Up-Coming Studio | Brand New I Handover March 2026": "即将上线单身公寓 | 全新房源 | 2026年3月交房",
  "Available Soon | Best Amenities | Direct Owner | No Commission": "即将起租 | 设施一流 | 房东直租 | 免佣金",
  "Vacant Studio | Prime Location | Tawtheeq Avli": "空置单身公寓 | 黄金地段 | 可办 Tawtheeq",
  "Vacant | Prime Location | From Owner | Tawtheeq": "空置 | 黄金地段 | 房东直租 | 可办 Tawtheeq",
  "Stunning Studio | Modern | Available for Rent": "精美单身公寓 | 现代装修 | 待租",
  "Nice & Clean Apartment I Corner I Single Row I GF": "整洁公寓 | 边户 | 独栋单排 | 底层",
  "COOL COMMUNITY AMAZING FACILITIES PRIME LOCATION": "优质社区，设施完备，黄金地段",
  "Corner Unit l Huge Garden l Huge Unit": "边户单元 | 超大花园 | 超大面积",
  "Modern Studio in Baniyas, Close to Bawabat Al Shar": "Baniyas 现代单身公寓，靠近 Bawabat Al Sharq",
  "VACANT / HOT DEAL / FLEXIBLE PAYMENTS": "空置 / 热门优惠 / 灵活付款",
  "Spacious 1BHK With Separate Kitchen Excellent Rooms Size Proper Washroom Khalifa City a": "Khalifa City A 宽敞一室一厅，独立厨房，房间宽大，卫浴整洁",
  "European Compound Luxury 1Bedroom+Kitchen+Bath +Free WIFI 4800-monthly": "欧式大院豪华一居室 | 含厨卫 | 免费 WiFi | 月租 4800",
  "Bright & Spacious One Bedroom Hall Apartment": "采光极佳且宽敞的一室一厅公寓",
  "BRAND NEW SPACIOUS APARTMENT AVAILABLE IN MBZ": "MBZ 全新宽敞公寓招租",
  "Brand New One Bedroom Hall With Shared Terrace Sep/Kitchen & Luxury Washroom On a Prime Location In KCA": "KCA 黄金地段全新一室一厅，带共享露台，独立厨房及豪华卫浴",
  "BRAND NEW ONE BEDROOM HALL PROPER KITCHEN & WASHROOM | IN A PRIME LOCATION IN MBZ": "MBZ 黄金地段全新一室一厅，带独立厨卫",
  "New 01 Bedroom Hall Apartment for Family | Al Rahba": "Al Rahba 全新一室一厅公寓，适合家庭居住",
  "Luxurious 01:Bedroom Hall": "豪华一室一厅",
  "Spacious One bedroom hall in Al Shahama Abudhabi": "Abu Dhabi, Al Shahama 宽敞一室一厅",
  "Affordable | Wardrobes | Prime Location": "价格亲民 | 带衣柜 | 黄金地段",
  "Spacious 1BR | Balcony | Up to 4 Payments | Hot Deal": "宽敞一居室 | 带阳台 | 最多可4次付款 | 热门特惠",
  "Excellent 1BHK Apartment | First Floor | Madinat Al Riyadh City": "Madinat Al Riyadh City 优质一室一厅 | 一楼",
  "SPACIOUS! 1-BEDROOM HALL WITH HUGE BALCONY AVAILABLE IN MBZ CITY": "宽敞！MBZ City 带超大阳台的一室一厅",
  "SPACIOUS 1BR APARTMENT FOR EXECUTIVE BACHELORS | READY TO MOVE | ME-11": "ME-11 宽敞一居室，适合白领人士 | 即可入住",
  "Mega Offer! Only 50K Yearly Spacious 1-BHK Flat near Al Wahda Mall in Abu Dhabi": "超值特惠！Abu Dhabi, Al Wahda Mall 附近宽敞一室一厅，年租仅5万",
  "Spacious 1BHK Apartment for Rent | Water & Electricity Included | Al Khalidiyah (Near Khalidiyah Mall)": "Al Khalidiyah (靠近 Khalidiyah Mall) 宽敞一室一厅出租 | 包水电",
  "Magneficent Layout | Italian Kitchen | Ready To Move": "极佳户型 | 意式厨房 | 即可入住",
  "1BR with Balcony | Available Now | Premier Pick": "带阳台一居室 | 即刻起租 | 优质推荐",
  "Super Class 1BHK with Private Terrace At 1st Floor": "高端一室一厅，带私家露台，位于一楼",
  "1BR with Balcony | Good Community | Flash Deals!": "带阳台一居室 | 优质社区 | 限时特惠！",
  "Spacious 1-Bedroom Flat in Prime Location": "黄金地段宽敞一居室公寓",
  "Wide Space 1BR with Balcony | Hot Offer of the Month": "宽敞一居室带阳台 | 本月特惠",
  "Brand new Private Entrance | 1BHK Apt | Ready to move": "全新独立入口 | 一房一厅 | 拎包入住",
  "Brand New | Spacious | Ready To Move | Separated Kitchen": "全新 | 空间宽敞 | 随时入住 | 独立厨房",
  "MONTHLY RENT 5000 ONLY BRAND NEW 1BHK AVAILABLE IN RIYADH CITY": "月租仅 5000，RIYADH CITY 全新一房一厅房源",
  "1BR with Good Facilities | Great Community | Affordable": "设施齐全的一居室 | 优质社区 | 价格实惠",
  "BRAND NEW ONE BEDROOM APARTMENT": "全新一居室公寓",
  "Excellent Sunny 1 Bedroom Hall With Separate Kitchen Big Windows Spacious Bath Tub In KCA": "KCA 采光极佳一房一厅，带独立厨房、大窗户及宽敞浴缸",
  "Duplex Flat including water & electricity": "复式公寓，包水电",
  "AMAZING SEA VIEW ◆ WONDERFUL WATERFRONT LOCALITY": "绝美海景 ◆ 迷人滨水地段",
  "Studio Apartment With Water & Electricity Included": "开间公寓，包水电",
  "Fully Furnished Studio Apartment With Water & Electricity": "全家具精装开间，包水电",
  "PRIVATE ENTRANCE! Fully Furnished Studio Apartment With Water & Electricity Included": "独立入口！全家具精装开间，包水电",
  "Prime Location | Big Layout | Community View": "黄金地段 | 户型宽敞 | 社区景观",
  "Fully Furnished Studio Flat with Parking | Monthly AED 5,000 | Near Al Wahda Mall, Abu Dhabi": "Abu Dhabi Al Wahda Mall 附近精装开间，带车位 | 月租 5,000 迪拉姆",
  "Fully furnished | With parking. | Brand New | Hot Deal": "全家具 | 带车位 | 全新 | 特惠房源",
  "Studio In Arc Tower with Best Facilities in Al Reem Island": "Al Reem Island Arc Tower 精装开间，配套顶级设施",
  "GET THE DEAL◆AMAZING LOCATION◆MOVE NOW◆HOT PRICE": "抢购房源◆核心位置◆随时入住◆超值价格",
  "BEAUTIFUL FULLY FURNISHED STUDIO APARTMENT AVAILABLE AT OPPOSITE MADINAT ZAYED MALL READY TO MOVE": "MADINAT ZAYED MALL 对面精美全家具开间，拎包入住",
  "ELEGANT QLTY FULLY FURNISHED STUDIO IN BATEEN AREA.": "BATEEN AREA 高品质精装开间",
  "Vacant | Un Furnished | High Floor": "空置 | 简装 | 高楼层",
  "Fully Furnished Studio with balcony In Al khalidiyah , Zayed the first street, / 6200 Monthly": "Al khalidiyah Zayed the first street 精装带阳台开间 | 月租 6200",
  "Stunning Fully Furnished Studio In Alreem Island, Marina Highest City View, / 7499 Monthly": "Alreem Island Marina 绝美精装开间，高层城市景观 | 月租 7499",
  "Partial Canal View ◆Lavish Layout ◆Great Amenities": "部分运河景观 ◆ 豪华户型 ◆ 设施齐全",
  "BRAND NEW FULLY FURNISHED 1BHK WITH BALCONY IN KCA": "KCA 全新精装一房一厅带阳台",
  "Brand new-Modern spacious 1/BHK | Sep.kitchen | Modern bath | Parking": "全新现代宽敞一房一厅 | 独立厨房 | 现代卫浴 | 带车位",
  "European Community Luxury 1BHK Fully Furnished Proper Washroom KCA": "KCA 欧式社区豪华精装一房一厅，带标准卫浴",
  "COOL COMMUNITY◆AMAZING FACILITIES◆NEAR DUBAI": "优质社区 ◆ 设施一流 ◆ 近 DUBAI",
  "Fully Furnished 1-Bedroom With Water & Electricity Included": "全家具精装一居室，包水电",
  "PRIVATE ENTRANCE! Fully Furnished 1-Bedroom With Water & Electricity Included": "独立入口！全家具精装一居室，包水电",
  "Big Deal! Only 60K/Year! Beautiful 1-BHK C/AC Flat on Hamdan St. Chiller Free": "超值！年租仅 60K！Hamdan St. 精美一房一厅，中央空调免制冷费",
  "AMAZING DEAL | 1 BHK | Brand New": "超值优惠 | 一房一厅 | 全新",
  "Excellent 1 BHK Available in Airport Road with 2 Bathrooms and Balcony": "Airport Road 优质一房一厅，两卫带阳台",
  "1BHK 2 Bathrooms Apartment For Rent in 6 Payments": "两卫一房一厅，支持 6 次付款",
  "LUXURIOUS 1 BEDROOM APARTMENT IN MBZ CITY": "MBZ CITY 豪华一居室公寓",
  "RENOVATION ONE BEDROOM HALL APARTMENT AVAILABLE AT AL FALAH STREET BACKSIDE SUDANI CLUB": "AL FALAH STREET SUDANI CLUB 后侧全新装修一房一厅",
  "Huge 1BHK brand new building wardrobe": "全新楼盘超大一房一厅，带衣柜",
  "Extensive 1BHK with Tawtheeq | Parking AV | No agant Fee | Ready to Occupied": "超大一房一厅带 Tawtheeq 认证 | 有车位 | 免中介费 | 随时入住",
  "Deluxe 1 Bedroom Hall Apartment 2 Bathrooms Balcony Prime Location TCA": "TCA 黄金地段豪华一房一厅，两卫带阳台",
  "Premium Furnished One Bedroom Apartment In Mamoura Complex, Al Nahyan Camp, Near Main Bus Station / 7,500 Monthly": "Al Nahyan Camp Mamoura Complex 高端精装一居室，近主巴士站 | 月租 7,500",
  "Amazing 1 BHK Available in Tourist club": "Tourist club 极佳一房一厅房源",
  "Spacious One-bedroom Hall apartment for rent al Murror": "Al Murror 宽敞一房一厅出租",
  "Ready-to-move-in 1 BHK": "拎包入住一房一厅",
  "Limited Offer | Modern & Stylish Apartment | Basement Parking | Ready to Move": "限时优惠 | 现代时尚公寓 | 地下车位 | 随时入住",
  "Bright 01 Bed Apt with 02 Bathrooms and Wardrobes for 65k at Nahyan": "Nahyan 采光极佳一居室，两卫带衣柜，年租 65k",
  "Stylish Fully Furnished 1 Bedroom Apartment Located in Al Falah/ 7500 AED Monthly": "Al Falah 时尚精装一居室 | 月租 7500 迪拉姆",
  "Wonderful Fully Furnished Studio In Al khalidiyah , Zayed the first street, / 4800 Monthly": "Al khalidiyah Zayed the first street 优质精装开间 | 月租 4800",
  "Spacious Fully Furnished Studio Apartment With Water & Electricity Included": "宽敞全家具精装开间，包水电",
  "FULLY FURNISHED!! Studio Apartment With Water & Electricity Included": "全家具！！精装开间，包水电",
  "Super Clean Furnished Studio with Separate Sitting Area": "超整洁精装开间，带独立休息区",
  "COOL COMMUNITY◆AMAZING FACILITIES◆PRIME LOCATION": "优质社区 ◆ 设施一流 ◆ 黄金地段",
  "✨ Modern Furnished Studio – First Tenant | Khalifa City A ✨": "✨ 现代精装开间 – 首租 | Khalifa City A ✨",
  "AMAZING DEAL | Studio | |Brand New": "超值优惠 | 开间 | 全新",
  "AMAZING DEAL | BOOKING NOW": "超值优惠 | 即刻预订",
  "Modern Studio with Large Private Balcony – Khalifa City -": "Khalifa City 现代开间，带超大私家阳台",
  "Studio from owner directly": "房东直租开间",
  "Big Deal! Only 4,200/month! C/AC Studio Flat in Tower Bldg. on Electra St. with Water, Elect. and W": "超值！月租仅 4,200！Electra St. 大厦精装开间，包水电网及中央空调",
  "BEAUTIFUL ONE BEDROOM HALL APARTMENT AVAILABLE AT AL NAHYAN READY TO MOVE": "AL NAHYAN 精美一房一厅，随时入住",
  "Specious Studio Apartment In Building At Prime Location": "黄金地段大厦宽敞开间",
  "Super Clean Furnished Studio with Separate entrance": "超整洁精装开间，带独立入口",
  "Superb Fully Furnished Suite In Alreem, City View, / 5800 Monthly": "Alreem 极佳精装套房，城市景观 | 月租 5800",
  "READY TO MOVE SPECIOUS STUDIO": "随时入住宽敞开间",
  "EXCLUSIVE 1BHK AVAILABLE IN MBZ ZONE 6 BEHINDBURJEEL,MAZYAD MALL /(MONTHLYRENT 4500) (ASIANS ONLY)": "MBZ ZONE 6 Mazyad Mall 后面 Burjeel 附近独家一房一厅 | 月租 4500 (仅限亚洲人)",
  "Huge 1BHK free W&E behind burjeel": "Burjeel 后侧超大一房一厅，免水电费",
  "Excellent 1BHK Apartment available including water electricity and maintenance": "优质一房一厅，包水电及物业费",
  "🏠 Excellent 1BHK Apartment | First Floor | Madinat Al Riyadh City": "🏠 优质一房一厅 | 一楼 | Madinat Al Riyadh City",
  "Amazing 1BhK in villa neat and clean All included rent for family": "别墅内优质一房一厅，整洁干净，费用全包，适合家庭",
  "Newly Renovating spacious 1BHk in muroor area near khalifa university In Villa All included": "Muroor 地区 Khalifa University 附近别墅内全新装修宽敞一房一厅，费用全包",
  "🏡 Super Class 1BHK with Private Terrace At 1st Floor": "🏡 高档一房一厅，带私家露台，位于一楼",
  "Available Soon I Prime Location I Zero Commission": "即将起租 | 黄金地段 | 零佣金",
  "Live Between the Beach+ Museum | Stylish Studio": "漫步沙滩与博物馆之间 | 时尚开间",
  "Todays'  offer -18 Feb - Big Size- Ready to move": "今日特惠 - 2月18日 - 超大空间 - 拎包入住",
  "High-Demand Furnished Studio in Prime Al Reem Area": "Al Reem 核心区热门精装开间",
  "Studio Apartment In Zafaranah / Monthly 6499/-AED": "Zafaranah 开间公寓 | 月租 6499 迪拉姆",
  // PF-specific titles not in Bayut/Dubizzle
  "Modern 1BHK W/Balcony  | No Commission": "现代一居室带阳台 | 免佣金",
  "Charming Furnished 1BR Apartment in The Gate": "The Gate 迷人带家具一居室",
  "Ferrari World View | Upcoming 15Fab 26 | Book Now": "法拉利世界景观 | 2月15日可租 | 立即预订",
  "Bright 1 BR  - Direct from the owner - Free ADDC": "明亮一居室 - 房东直租 - 免水电费",
  "Vacant | 1BHK Lofts | Ground Floor | Rent Now !": "空置 | 复式一居室 | 底层 | 立即租赁！",
  "1 BR Pool View | Vacant | Great View !!!": "一居室泳池景观 | 空置 | 绝佳景观！！！",
  "Available Soon I From Owner I Prime Location": "即将空置 | 房东直租 | 黄金地段",
  "Sleek 1 BHK | Prime Location | No Commission": "时尚一居室 | 黄金地段 | 免佣金",
  "Modern 1BHK | Free ADDC | 0% Commission  Hot Deal": "现代一居室 | 免水电费 | 零佣金 特价",
  "PREMIUM DEAL! Fully Furnished | Balcony | 1Parking": "优质房源！精装 | 阳台 | 含停车位",
  "ELEGANT 1BHK NO ADDC NO AGENT FEE TAWTHEQ PARKING": "优雅一居室 免水电费 免中介费 含合同备案 含停车位",
  "No Commission Elegant 1BHK Spacious & Affordable": "免佣金 优雅一居室 宽敞实惠",
  "Furnished 1BR | Ground Level | Modern Living": "带家具一居室 | 一楼 | 现代生活",
  "Amazing Deal | Limited Time Offer | Rent Now!!": "超值优惠 | 限时特价 | 立即租赁！！",
  "1st Floor l Hot Deal l Spacious 1BR": "二楼 | 特惠 | 宽敞一居室",
  "Smart Choice | Private Community Lifestyle | Ideal": "明智之选 | 私人社区生活 | 理想居所",
  "Hot Deal! Hydra Studio | Furnished | Vacant | 65K": "热门特惠！Hydra 单身公寓 | 带家具 | 空置 | 6.5万",
  "Modern Studio With Furnished | City Views": "现代精装开间 | 城市景观",
  "HOTTT PRICE!! Beautiful View | Furnished Studio": "超值价格！！美丽景观 | 精装开间",
  "Studio Apartment In Zafaranah / Monthly 6499/-AED": "Zafaranah 开间公寓 | 月租 6499 迪拉姆",
  "Partial Canal View | Modern Studio +Balcony | Yas": "部分运河景 | 现代开间+阳台 | Yas",
  "Where Waves Whisper and Coastal Luxury Awaits": "聆听海浪低语 尊享滨海豪华生活",
  "Fully Furnished | Studio | Ready to move in": "家具齐全 | 开间 | 即可入住",
  "Upcoming| Elegant Unit| Mangrove Views|Prime Area": "即将推出 | 优雅单元 | 红树林景观 | 黄金地段",
  "Spacious Layout | Prime Location | Move in Ready": "宽敞布局 | 黄金地段 | 即可入住",
  "Cozy Studio | Relaxing Partial Sea View | Vacant": "温馨开间 | 惬意侧面海景 | 空置",
  "VACANT | Urban View | Upto 4 Payments | High Floor": "空置 | 都市景观 | 最多4期付款 | 高层",
  "Sea View Studio | Brand New Furniture | Negotiable": "海景开间 | 全新家具 | 可议价",
  "Best Priced Studio Fully Furnished Home | Book Now": "性价比最高带家具开间 | 立即预订",
  "Fully Furnished | Stunning Views | Ready for you": "家具齐全 | 绝佳景观 | 为您准备",
  "Relaxation Lifestyle | Great Community | Inquire!": "休闲生活方式 | 优质社区 | 立即咨询！",
  "Brand New Studio w/ Parking & Amenities": "全新开间 含停车位及配套设施",
  "Fully Furnished Studio | Mangrove View |High Floor": "精装开间 | 红树林景观 | 高层",
  "Outstanding Home / Mall View": "出色住宅 / 商场景观",
  "Hot Offer>1BHK >Wardrobes>Huge size": "热门优惠 > 一居室 > 带衣柜 > 超大面积",
  "Spacious 1 BHK Apartment with Utilities included": "宽敞一居室公寓 含水电费",
  "Fully Furnished 1 Bedroom / Al Falah 7500 Monthly": "Al Falah 精装一居室 月租 7500",
  "UNFURNISHED 1BED | 2 PAYMENTS | POOL PARKING": "毛坯一居室 | 2期付款 | 泳池停车位",
  "Special Offer | Immediate Move-In | 58K": "特别优惠 | 即刻入住 | 58K",
  "Up Coming unit  - Prime Location - 0% Commission -": "即将推出 - 黄金地段 - 零佣金",
  "Your Ideal Home Awaits | Contemporary 1BHK – ALG2": "您的理想之家 | 现代一居室 – ALG2",
  "Elegant Tawtheeq Available 0 Commission Free Bill": "优雅公寓 可办合同备案 零佣金 包账单",
  "Upcoming Tawtheeq Available 0 Bills 0 Commission": "即将推出 可办合同备案 包账单 零佣金",
  "1 BR | Pool View | Large Balcony | Ready Soon": "一居室 | 泳池景观 | 大阳台 | 即将可租",
  "PRIME LOCATION 1BHK APARTMENT WITH ALL FACILITIES": "黄金地段一居室公寓 设施齐全",
  "Furnished Studio Apartment in Al Reem / 7.5k M": "Al Reem 精装开间 月租 7.5k",
  "Ready To Move ! Stunning Layout ! Inquire Now": "随时入住！绝佳户型！立即咨询",
  "⇛ Prime Area ⇛ Spacious Unit ⇛ Ready To Move ⇚": "⇛ 黄金地段 ⇛ 宽敞单元 ⇛ 即可入住 ⇚",
  "Low Price | Modern Unit | Prime Location | Vacant!": "低价 | 现代单元 | 黄金地段 | 空置！",
  "Spacious Studio | Modern Urban Living | Book Now": "宽敞开间 | 现代都市生活 | 立即预订",
  "Fully Renovated| Upgraded Kitchen and Bath": "全面翻新 | 升级厨卫",
  "Type C | Relaxation Mode on | Spacious Unit |": "C户型 | 休闲模式 | 宽敞单元",
  "luxury|Furnished1BHK|Sep Kitchen|Monthly 5700/|KCA": "豪华|精装一居室|独立厨房|月租5700|KCA",
  "Offer Free Bills Tawtheeq Available No Commission": "包账单 可办合同备案 免佣金",
  "Rare & Spacious Unit /Prime Hamdan Street": "稀缺宽敞单元 / Hamdan Street 黄金地段",
  "1 Bed First Floor | Vacant Unit | Best Community": "一居室二楼 | 空置 | 最佳社区",
  "RDM PRIME LOCATION FROM OWNER NO AGENT FEE TAWTHIQ": "即可入住 黄金地段 房东直租 免中介费 可办合同备案",
  "European Luxury 1BHK+Backyard+Free WIFI+4700-Month": "欧式豪华一居室+后院+免费WiFi+月租4700",
  "BOOK NOW!! AVAILABLE END JAN - TYPE E - 72K ONLY": "立即预订！！一月底可租 - E户型 - 仅72K",
  "Charming 1 BR Junior | Elegant Community": "迷人精致一居室 | 优雅社区",
  "Al Muntazah 1 BR Apartment": "Al Muntazah 一居室公寓",
  "Spacious One-Bedroom /Tawtheeq Available/Free Bill": "宽敞一居室 / 可办合同备案 / 包账单",
  "Hot Offer | 1BHK | Newly Renovated": "特别优惠 | 一居室 | 新翻修",
  "EUROPEAN STYLE 1BHK WITH HUGE KITCHEN AND WASHROOM": "欧式风格一居室 带超大厨房和卫生间",
  "Charming 1 BR Apartment in Khalifa City A": "Khalifa City A 迷人一居室公寓",
  "HURRY UP!!! 1 BED POOL VIEW 60000 ONLY": "抓紧机会！！！泳池景一居室 仅60000",
  "Spacious 1 BR Apartment in Bawabat Al Sharq": "Bawabat Al Sharq 宽敞一居室公寓",
  "Hot Deal  | Ready to Move In | With Balcony": "特价优惠 | 即可入住 | 带阳台",
  "LOWEST PRICE- 1 BED APARMENT FOR RENT- 63000 ONLY": "最低价 - 一居室出租 - 仅63000",
  "Bright Studio | Fountain View | Prime Location": "明亮开间 | 喷泉景观 | 黄金地段",
  "Sea View | Move In Ready | Good Condition": "海景 | 即可入住 | 状况良好",
  "Modern  | Excellent Condition |Top Tier Ameneties": "现代 | 状态极佳 | 顶级设施",
  "Ready to Move | Spacious | Sea World View": "即可入住 | 宽敞 | 海洋世界景观",
  "Hot Deal | Ready To Move In | Prime Spot": "特惠房源 | 即可入住 | 黄金地段",
  "Prime location / tawtheeq AV / No Commission": "黄金地段 / 可办合同备案 / 免佣金",
  "Balcony | Flexible Payments | Ready to Move": "阳台 | 灵活付款 | 即刻入住",
  "Fully Furnished | Mangrove View | High Floor": "全家具 | 红树林景观 | 高楼层",
  "Vibrant | Furnished Studio | Sea View | Vacant": "活力 | 带家具 开间 | 海景 | 空置",
  "Brand New One Bedroom studio for rent in Building in MBZ ME10": "位于 MBZ ME10 大楼的全新 一居室 开间 出租",
  "Brand new-Amazing cozy 1/BHK | Wardrobe | Bathtub | Sep. kitchen | covered parking": "全新-绝佳舒适 一居室 | 衣柜 | 浴缸 | 独立厨房 | 室内停车位",
  "Brand new|High finishing|1BHK|Private entrance|Covered parking|Modern|Ready to move|Separate kitchen and bathroom": "全新|高级装修|一居室|独立入口|室内停车位|现代|即刻入住|独立厨卫",
  "Exclusive | Brand new 1/BHK | Sep. kitchen | modern bath | Ready to move | Parking": "独家 | 全新 一居室 | 独立厨房 | 现代卫浴 | 即刻入住 | 停车位",
  "Brand new|High finishing|1BHK|Private entrance|Covered parking|Modern|Ready to move|Separate kitche": "全新|高级装修|一居室|独立入口|室内停车位|现代|即刻入住|独立厨房",
  "Exclusive | Brand new 1/BHK | Sep.kitchen | modern bath | Ready to move | Parking": "独家 | 全新 一居室 | 独立厨房 | 现代卫浴 | 即刻入住 | 停车位",
  "Todays' offer -18 Feb - Big Size- Ready to move": "今日特惠 - 2月18日 - 大户型 - 即可入住",
  "Limited Offer | Vacant |  1 Payment": "限时优惠 | 空置 | 1期付款",
  "Vacant Now | Modern Layout | Ideal location": "现已空置 | 现代布局 | 理想地段",
  "Tremendous 1BHK With Closed Kitchen & Spacious Saloon": "超大一居室 带封闭式厨房及宽敞客厅",
  "Up-Coming || Prime Location || 0%commission || Tawtheeq Available": "即将推出 || 黄金地段 || 零佣金 || 可办 Tawtheeq",
  "Brand New Studio Apartment | The Gate Masdar City": "全新开间公寓 | The Gate 马斯达尔城",
  "Spacious Studio | Vibrant Community | Flexible Payment Plan": "宽敞开间 | 活力社区 | 灵活付款方案",
  "Brand new-Amazing cozy 1/BHK | Wardrobe | Bathtub | Sep.kitchen | covered parking": "全新-舒适一居室 | 衣柜 | 浴缸 | 独立厨房 | 室内停车位",
  "Hot Deal 1BR Prime Layout in Wifaq Tower!": "特惠一居室 Wifaq Tower 优质户型!",
  "Spacious 1BHK Apartment for Rent | Water & Electricity Included | Al Khalidiyah ,Near International": "宽敞一居室出租 | 包水电 | Al Khalidiyah 靠近国际区",
  "Spacious 1 Bedroom Apartment for Rent in Musaffah Shabiya 10 With Balcony": "穆萨法 Shabiya 10 宽敞一居室出租 带阳台",
  // ─── Batch 2026-02-25 (Gemini-translated, 71 titles) ──────
  "1bhk Excellent ventilation in Mohammed Bin Zayed": "Mohammed Bin Zayed 通风极佳的一房一厅",
  "4Payments | Spacious 1BR | Gym N Pool | Balcony": "4次付款 | 宽敞一房 | 健身房和泳池 | 阳台",
  "Al Mushrif Bright 1 BR Apartment": "Al Mushrif 采光良好的精美一房公寓",
  "Al Mushrif Villas 1 BR Apartment": "Al Mushrif Villas 一房公寓",
  "Amazing One Bed Room 4800 Mohamed Bin zayed City": "Mohamed Bin zayed City 超赞一房 4800",
  "BRAND NEW 1-BEDRM HALL MAJLIS WITH 2 BATH": "全新一房一厅一卫带议事厅 (Majlis)",
  "Best Deal Al Reem Island | Bright & Spacious 1Br": "Al Reem Island 最优交易 | 宽敞明亮一房",
  "Canal & City View- 1Br- Multiple payments Options": "运河与城市景观 - 一房 - 多种付款方式",
  "Deluxe 1BHK | Free ADDC | NO COMMISSION": "豪华一房一厅 | 免 ADDC 费用 | 无佣金",
  "European Society, Apartment Furnished Studio Sep Kitchen| 4500-Monthly Near Mall KCA": "欧式社区，精装单身公寓带独立厨房 | 每月 4500 近 KCA 商场",
  "European Styles 1BHK+Free WIFI+Kitchen+Bath 4600\\M": "欧式风格一房一厅 + 免费 WIFI + 厨房 + 浴室 每月 4600",
  "FULLY FURNISHED | SEA VIEW | READY TO MOVE": "家具齐全 | 海景 | 随时入住",
  "Furnished Studio Al Khalidiyah / 6k Monthly": "Al Khalidiyah 精装单身公寓 / 每月 6k",
  "Furnished Studio In Alreem Island / 7499 Monthly": "Alreem Island 精装单身公寓 / 每月 7499",
  "Furnished Suite In Alreem/ 5800 Monthly": "Alreem 精装套房 / 每月 5800",
  "Good Price | Versatile & Functional Unit | Vacant!": "价格优惠 | 多功能实用户型 | 空置中！",
  "HOT DEAL! | Prime Location | 1 Parking": "特惠房源！ | 黄金地段 | 1个停车位",
  "HOT DEAL!! Stylish 1BR | Available from MAR 12": "特惠房源！！时尚一房 | 3月12日起租",
  "HOTTEST PRICE!! 2 Cheques | Higher Floor |Call Now": "最低价格！！2张支票付款 | 高层 | 立即咨询",
  "High Floor Studio | Flexible Payments | Al Reem": "高层单身公寓 | 灵活付款 | Al Reem",
  "High Floor | Huge Furnished & Unfurnished": "高层 | 超大精装及简装可选",
  "Hot Deal I Many Payment IUpcomingI Prime  Location": "特惠房源 | 多种付款方式 | 即将推出 | 黄金地段",
  "Hot Deal | Ready to Move In | With Balcony": "特惠房源 | 随时入住 | 带阳台",
  "Hot Offer / Fully Furnished / Sea View / Occupy It": "特供优惠 / 家具齐全 / 海景 / 即可入住",
  "Hot Offer 1 Bed Hall Apart with Wardrobes And Chiller Free Available in Shabiya 9": "特供优惠 Shabiya 9 一房一厅带衣柜且免空调费",
  "Hot Price on This Charming Bright Unit": "这套采光极佳的精美房源价格超值",
  "LOVELY 1 BEDROOM DIRECT OWNER ADDC FEE": "精美一房 业主直租 含 ADDC 费用",
  "Lavish 1 Bedroom and Hall|Monthly4800|Free Wi-Fi": "豪华一房一厅 | 每月 4800 | 免费 Wi-Fi",
  "Lavish Fully Furnished 1BR|Private Entrance|M6200|": "豪华精装一房 | 独立入口 | 每月 6200",
  "Limited Offer: Modern 1-Bd Hot Deal": "限时优惠：现代一房特惠房源",
  "Limited offer | 1 Bedroom Apt | Facilities | Parking": "限时优惠 | 一房公寓 | 配套齐全 | 带车位",
  "Low Price! | Elegant Finish | Prime Area | Vacant!": "低价房源！ | 装修典雅 | 黄金区域 | 空置中！",
  "Luxurious Living | Modern style | Prime location": "豪华生活 | 现代风格 | 黄金地段",
  "Mangrove View | High Floor | Flexible Payments": "红树林景观 | 高层 | 灵活付款",
  "Mangrove View | Move-in Ready | Up to 2 Payments": "红树林景观 | 随时入住 | 最多 2 次付款",
  "Mangrove View | Prime Location | Ready to Move": "红树林景观 | 黄金地段 | 随时入住",
  "Massive Studio I 2 Big Balcony I Ready to move |": "超大单身公寓 | 2个大阳台 | 随时入住",
  "Modern 1BHK | Free ADDC No Commission Hot Deal!": "现代一房一厅 | 免 ADDC 费用 无佣金 特惠房源！",
  "Modern 1BHK | Free ADDC | 0% Commission- Brand New": "现代一房一厅 | 免 ADDC 费用 | 0 佣金 - 全新",
  "Modern BR Unit | Canal View | Premium Location": "现代房源 | 运河景观 | 优越地段",
  "NO COMMISSION  SPACIOUS 1 BR  2 Bath in Al REEM ISLAND -SEA FACE TOWER": "无佣金 Al REEM ISLAND - SEA FACE TOWER 宽敞一房两卫",
  "Nice 1BHK Apt With Basement Parking 2 Bathroom": "精美一房一厅公寓 带地下车位 两卫",
  "Partial Sea Views | Modern Studio | 4 Cheques": "部分海景 | 现代单身公寓 | 4张支票付款",
  "Prime Location / Newly Built Unit / 0 % Commission": "黄金地段 / 新建房源 / 0 佣金",
  "Prime Location\\ bills included \\ pets allowed": "黄金地段 包水电费 允许携带宠物",
  "Ramadan Offer| Very Big Size Home Fully Furnished": "斋月优惠 | 超大户型 家具齐全",
  "Ready Loft 1BR+Terrace | Vacant | Very Good Price": "精装修 Loft 一房带露台 | 空置 | 价格极佳",
  "Ready to move in 1BHK in Marina Bay Reem Island": "Marina Bay Reem Island 一房一厅 随时入住",
  "SPACIOUS 1 BED | 4 PAYMNTS | GYM POOL | NO PARKING": "宽敞一房 | 4 次付款 | 健身房泳池 | 无车位",
  "SPACIOUS 1-BEDRM HALL WITH HUGE BALCONY IN MBZ CIT": "MBZ CIT 宽敞一房一厅带超大阳台",
  "Sea View Fully Furnished in Al Reem/5600 Monthly": "Al Reem 海景精装房 / 每月 5600",
  "Spacious 1BHK With Separate Kitchen Sunlight Windows Excellent Rooms Size Proper Washroom Khalifa City a": "Khalifa City a 宽敞一房一厅带独立厨房 采光充足 房间宽大 独立卫浴",
  "Spacious 1BHK with 2 Baths & Basement Parking | Shabiya 12": "Shabiya 12 宽敞一房一厅两卫 带地下车位",
  "Spacious 1BR | Upcoming Unit | Prime Location": "宽敞一房 | 即将推出 | 黄金地段",
  "Spacious One Bedroom+Hall|Near Forsan Central Mall": "宽敞一房一厅 | 近 Forsan Central Mall",
  "Spacious Studio | Gate Tower 1 | Water View": "宽敞单身公寓 | Gate Tower 1 | 水景",
  "Studio | Spicious Layout | Sea view | Vacant": "单身公寓 | 布局宽敞 | 海景 | 空置",
  "Superior Furnished | Exceptional | Ready To Move": "高档精装 | 品质卓越 | 随时入住",
  "Type D 1BR| Vacating Next Month| Book It Now": "D型一房 | 下月空出 | 立即预订",
  "Type D | Upcoming 1BR | Ideal Community": "D型 | 即将推出一房 | 理想社区",
  "UN-FURNISHED | READY TO MOVE": "简装/无家具 | 随时入住",
  "Unit Tawtheeq !! 1-Bedroom | American Kitchen | Private Balcony | Share Pool | Basement Parking": "带 Tawtheeq 认证！一房 | 开放式厨房 | 私人阳台 | 公用泳池 | 地下停车",
  "Up Coming | City and Mangrove View | Great Deal": "即将推出 | 城市与红树林景观 | 超值交易",
  "Urgent Rental | Furnished | Modern Studio": "急租 | 精装 | 现代单身公寓",
  "Vacant / Mangrove view / Great Facilities": "空置 / 红树林景观 / 设施齐全",
  "Vacant Now @ Duplex 1-Bedroom Apartment With Pvt Balcony | Shared Pool + GYM | Kitchen+ Washroom in Masdar City": "Masdar City 空置复式一房公寓 带私人阳台 | 共用泳池 + 健身房 | 厨房 + 卫浴",
  "Vacant Soon | High Floor | Book Now": "即将空出 | 高层 | 立即预订",
  "Vacant|Modern Studio|High Floor|Mangrove+Sea View": "空置 | 现代单身公寓 | 高层 | 红树林与海景",
  "Waterview-1BR Apt in Mangrove Place, Reem Island": "Reem Island, Mangrove Place 水景一房公寓",
  "Well Maintained 1BR | City View | Balcony access": "保养良好的一房 | 城市景观 | 可通阳台",
  "including all bills\\ Tawtheeq Avi\\No Commission": "包水电费 提供 Tawtheeq 无佣金",

  // ─── 2026-03-03 batch (Gemini-translated, 40 titles) ──────
  "12 PAYMENT | HOT DEAL 1 BR w/ BALCONY, POOL/GYM": "12期付款 | 热销特惠 1室带阳台，泳池与健身房",
  "1BR Duplex | Terrace | Ready to Move": "1室复式 | 带露台 | 拎包入住",
  "5000/- MONTHLY | NEW FULLY FURNISHED 1BHK | NR MALL IN KCA": "5000/月 | 全新精装全配1室1厅 | 靠近哈利法城A区(KCA)商场",
  "Amazing One Bed Room 4800  Mohamed Bin zayed City": "超赞一居室 4800 | 穆罕默德本扎耶德城(MBZ)",
  "BRAND NEW SPACIOUS APARTMENT AVAILABLE IN MBZ ASIANS ONLY ZONE 2,7,24,31,36": "全新宽敞公寓 | MBZ 2,7,24,31,36区 | 仅限亚洲人",
  "Best Deal  Al Reem Island | Bright & Spacious 1Br": "超值好房 丽姆岛(Al Reem) | 明亮宽敞1室",
  "Brand New Flat with Private Ent. in Shakhbout city": "全新公寓带独立入口 | 沙赫布特城(Shakhbout)",
  "Brand New One Bedroom - Prime location - 0 % Commission - Tawtheeq Available": "全新一居室 | 黄金地段 | 免中介费 | 可办Tawtheeq租赁合同",
  "Bright & Cozy 1BR | Three Payments | With Balcony": "明亮温馨1室 | 3期付款 | 带阳台",
  "Comfortable Fully Furnished Suite | No Commission": "舒适全配精装套房 | 免中介费",
  "Cozy Furnished Studio – Immediate Move-In": "温馨精装开间(Studio) | 随时入住",
  "Deluxe Furnished Suite | Free ADDC | NO COMMISSION": "豪华精装套房 | 免水电费(ADDC) | 免中介费",
  "Duplex | Exceptional | Ready To Move": "复式 | 优质房源 | 拎包入住",
  "Elegant 1BHK Apartment | Parking | Hot Offer": "典雅1室1厅公寓 | 带车位 | 热销特惠",
  "European Styles 1BHK+Free WIFI+Kitchen+Bath 4800\\M": "欧式1室1厅+免费WIFI+厨卫 4800/月",
  "Exceptional studio apartment | Free bills | Direct owner | No Commission": "优质开间公寓 | 免账单 | 房东直租 | 免中介费",
  "FABULOUS PRIVATE ENTRANCE ONE BEDROOM HALL PRESENTED BY LOGICAL COMMERCIAL BROKERS AT HEART OF MOHAMMAD BIN ZAYED CITY": "MBZ中心绝佳独立入口1室1厅 | Logical中介代理",
  "Furnished 80k|Unfurnished 75k |Share Pool|Balcony,": "带家具8万|无家具7.5万 | 共享泳池 | 带阳台",
  "HOT DEAL | 1 BHK w/ FULL FACILITY in AL REEM": "热销特惠 | 丽姆岛(Al Reem)1室1厅带全套设施",
  "HOT DEAL | 12 PAYMENT-1 BHK w/ BALCONY | LOW RENT": "热销特惠 | 12期付款-1室1厅带阳台 | 低租金",
  "HOT DEAL!! 85K/3 | Premium Tower | Pool View": "热销特惠!! 8.5万/3期 | 高级公寓楼 | 泳池景观",
  "HOT DEAL!!! Stylish 1 BR | Available from MARCH 12": "热销特惠!!! 时尚1室 | 3月12日起租",
  "HOT PRICE!! 2 Cheques | Higher Floor | Call Now": "惊喜价!! 2张支票(2期) | 高楼层 | 欢迎致电",
  "High Floor | Mangrove and Beach View": "高楼层 | 红树林与海滩景观",
  "Hot Deal | Prime Location | Bright and Spacious": "热销特惠 | 黄金地段 | 明亮宽敞",
  "Hot Deal! 1BR Apartment for RENT just 75K": "热销特惠! 1室公寓出租仅7.5万",
  "LIMITED TIME DEAL!!Two Payments | Partial Sea View": "限时特惠!! 2期付款 | 部分海景",
  "LUXURIOUS 1-BEDRM HALL AVAILABLE IN MBZ CITY": "豪华1室1厅 | 穆罕默德本扎耶德城(MBZ)",
  "Limited-Time Offer | No Commsission | Utilities Free | Great Location | Book Today": "限时特惠 | 免中介费 | 包水电 | 绝佳地段 | 立即预订",
  "M/5500 Brand New Fully Furnished One Bedroom Hall Sep/Kitchen Proper Washroom On Prime Location In": "5500/月全新精装1室1厅 独立厨房与标准卫浴 | 黄金地段",
  "M/5700 Brand New Fully Furnished One Bedroom Hall Sep/Kitchen Proper Washroom On Prime Location In KCA": "5700/月全新精装1室1厅 独立厨房与标准卫浴 | KCA黄金地段",
  "Neat And Clean 1bhk With Wardrobes & Separate Kitchen Mbz": "干净整洁1室1厅带衣柜及独立厨房 | MBZ",
  "PRIMIE LOCATION -READY TO MOVE-NO COMMISSION": "黄金地段 | 拎包入住 | 免中介费",
  "Prime location 1bhk / laundry room / open Kitchen": "黄金地段1室1厅 | 独立洗衣房 | 开放式厨房",
  "Pvt. balcony-Brand new modern 1/BHK | Sep. kitchen | Modern bath | parking": "私人阳台-全新现代1室1厅 | 独立厨房 | 现代卫浴 | 车位",
  "Ready To Move | Full Furnished | Flexible Payments": "拎包入住 | 全套家具 | 灵活付款",
  "Sleek Furnished Suite | Family Area | Free ADDC": "时尚精装套房 | 家庭区 | 免水电费(ADDC)",
  "Spacious studio | Large layout | Amazing view": "宽敞开间 | 大户型 | 绝佳景观",
  "Studio  Apartment /  Balcony Pool & Gym": "开间公寓 | 阳台 泳池与健身房",
  "UPCOMING MARCH ! 1 BHK | COMMUNITY VIEW | POOL VIEW | TOP NOTCH FACILITIES | CALL US NOW!!": "3月即将空出! 1室1厅 | 社区景观 | 泳池景观 | 顶级设施 | 欢迎致电!!",
  "1 BHK | Move-In Ready| 4 Payments": "一室一厅 | 拎包入住 | 可分四期付款",
  "4,200/-M -Brand New Furnished Studio With Shared Terrace Sep/Kitchen & Luxury Washroom On a Prime Location In KCA": "4200/月 - KCA黄金地段全新精装单身公寓 | 共享露台 | 独立厨房 | 豪华卫浴",
  "BEAUTIFUL ONE BEDROOM HALL APARTMENT AVAILABLE AT AL BATEEN READY TO MOVE": "Al Bateen 精美一室一厅公寓 | 拎包入住",
  "BEST DEAL! MANGROVE VIEW | HIGH FLOOR": "超值特惠！红树林景观 | 高楼层",
  "Brand New one bedroom Sep/kitchen Proper Washroom On prime location In KCA": "KCA黄金地段全新一居室 | 独立厨房 | 标准卫浴",
  "Brand new-Modern spacious 1/BHK | Elevator | Sep.kitchen | Modern bath | Parking": "全新现代宽敞一室一厅 | 电梯 | 独立厨房 | 现代卫浴 | 车位",
  "Cozy 1BR | Three Payments | With Balcony": "温馨一居室 | 可分三期付款 | 带阳台",
  "European Luxury 1Bedroom+Free WIFI+Kitchen 4800-M": "欧式豪华一居室+免费WIFI+厨房 | 4800/月",
  "HOT DEAL!! Stylish 1 BR | Available from MARCH 12": "热门房源！！时尚一居室 | 3月12日起租",
  "HOT PRICE!! Two Cheques | Higher Floor | Call Now": "特价！！两张支票付款 | 高楼层 | 立即致电",
  "Hot Price | Bright & Spacious 1Br| Ready to Move": "特价 | 宽敞明亮一居室 | 拎包入住",
  "Luxury Brand New1BHK with Sep Kitchen And Bath ...": "豪华全新一室一厅 | 独立厨房与卫浴 ...",
  "Outstanding Huge One Bed Room in Mohamed Bin zayed": "Mohamed Bin Zayed 超大优质一居室",
  "Prime Location - Ready To Move  in- No Commission": "黄金地段 - 拎包入住 - 免佣金",
  "Pvt.balcony-Brand new modern 1/BHK | Sep.kitchen | Modern bath | parking": "私人阳台 - 全新现代一室一厅 | 独立厨房 | 现代卫浴 | 车位",
  "VACANT|PRIME LOCATION|BIGGER LAYOUT": "空房 | 黄金地段 | 超大户型",
  // ─── Batch 2026-03-13 (Gemini-translated, 71 titles) ──────
  '1 BR APT | Type D | Available Soon': '一室公寓 | D户型 | 即将可租',
  '1 Bedroom Hall New Villa Al Bateen Area Khaldiiyah Abu Dhabi': '一室一厅新别墅 阿布扎比哈立迪亚阿尔巴廷区',
  '1 Bedroom Hall with Free water and electric Al Khalidiyah Abu Dhabi': '一室一厅免水电费 阿布扎比哈立迪亚',
  '1 Bedroom | Type C | Available For Rent': '一室 | C户型 | 现房出租',
  '1 PAYMENT HOT DEAL | 1 BHK w/ FULL FACILITY': '一次性付清特价 | 一室一厅带全套设施',
  '12-Cheques | Fully Furnished | En-Suite Bedroom': '可开12张支票 | 全带家具 | 带独立卫浴卧室',
  '1BHK Chiller-Free Flat for Rent in Shabiya 9 – AED 62K | 4 Payments': '沙比亚9区一室一厅免空调费公寓出租 – 6.2万迪拉姆 | 可分4次付款',
  '1BR APARTMENT | Behind Sheikh Zayed Grand Mosque | Al Rawdah, Abu Dhabi': '一室公寓 | 位于谢赫扎耶德大清真寺后方 | 阿布扎比阿尔罗达',
  '800 SQFT-7000 Per Month-1 BED SIZE SUITE | FURNISH': '800平方英尺-月租7000-一室面积套房 | 带家具',
  'Affordable Living in a Bright Cozy Space': '高性价比居住选择 明亮温馨空间',
  'Al Saada Street 1 BR Apartment': '萨达街一室公寓',
  'Amazing Brand New One Bed Room 4500 Monthly Zone19': '超赞全新一室 月租4500 19区',
  'Amazing Deal! High Floor Unit | Gated Community': '超值特价！高楼层单位 | 封闭式社区',
  'Amazing Rental Unit | Prime Al Remm Location |': '超赞出租单位 | 瑞姆岛黄金地段',
  'Available 1 Bedroom Type C | Prime Location | Affordable': 'C户型一室现房 | 黄金地段 | 高性价比',
  'BRAND NEW 1 BEDROOM HALL APARTMENT AVAILABLE IN MBZ CITY': '穆罕默德·本·扎耶德城全新一室一厅公寓出租',
  'Best Choice | Duplex | Flexible Payment': '最佳选择 | 复式 | 灵活付款',
  'Best Choice | Luxury Living | Negotiable |Call Now': '最佳选择 | 豪华居住 | 价格可议 | 立即致电',
  'Big 1 Bedroom Hall Apartment For Rent with Balcony in MBZ CITY': '穆罕默德·本·扎耶德城大户型一室一厅带阳台公寓出租',
  'Brand New Studio w/ Gym, Pool & Parking': '全新开间带健身房、泳池和停车位',
  'Brand new-Modern spacious 1/BHK | Elevator | Sep. kitchen | Modern bath | Parking': '全新现代宽敞一室一厅 | 电梯 | 独立厨房 | 现代卫浴 | 停车位',
  'CHARMING! 1-BEDROOM HALL AVAILABLE AT IDEAL LOCATION IN MBZ': '迷人房源！穆罕默德·本·扎耶德城理想地段一室一厅出租',
  'Call Now | Unique Living | Peaceful Community': '立即致电 | 独特居住体验 | 宁静社区',
  'Deluxe 1BHK W/Balcony | Free ADDC | NO COMMISSION': '豪华一室一厅带阳台 | 免水电费 | 无中介费',
  'Deluxe Tawtheeq Available 0 Commission Free Bills': '豪华房源提供租赁登记 0中介费 免账单',
  'Elegant Designed 1 BR | Laundry Room | Hot Offer': '优雅设计一室 | 洗衣房 | 热门特价',
  'European Community 1bhk PVt/Balcony Sep/Kitchen Proper Washroom On Prime Location In KCA': '哈利法城A区黄金地段欧洲社区一室一厅 独立阳台/独立厨房/正规卫浴',
  'European Society Style 1BHK With Separate Kitchen With Big Windows Sunlight Nice Bathroom In KCA': '哈利法城A区欧式风格一室一厅 带独立厨房/大窗户采光佳/精美卫浴',
  'Flexible Payment | High Floor | Private Balcony': '灵活付款 | 高楼层 | 私人阳台',
  'Fully Furnished / ready to move / City View': '全带家具 / 拎包入住 / 城市景观',
  'Fully Furnished 1 Bedroom / Al Falah 7200 Monthly': '全带家具一室 / 阿尔法拉 月租7200',
  'Furnished 65k and Unfurnished 60k| Shared Pool+GYM': '带家具6.5万/不带家具6万 | 共享泳池+健身房',
  'Furnished 80k |Unfurnished 75k |Share Pool+Balcony': '带家具8万 | 不带家具7.5万 | 共享泳池+阳台',
  'Furnished Studio Apartment': '带家具开间公寓',
  'Furnished Studio In Alreem Island / 5,500 Monthly': '瑞姆岛带家具开间 / 月租5500',
  'Furnished Studio with balcony | 5200 Monthly': '带家具开间配阳台 | 月租5200',
  'Furnished|1-BHK|Sep Kitchen|Pool|Parking|Balcony,,': '带家具|一室一厅|独立厨房|泳池|停车位|阳台',
  'HOT DEAL | 1BR Loft+Terrace | Vacant | BEST PRICE': '特价 | 一室Loft+露台 | 空置 | 最优价格',
  'HOT DEAL!! Stylish 1BR | Available from MARCH 12': '特价！！时尚一室 | 3月12日起租',
  'Hot Deal - Huge Size - Kitchen Appliances- parking': '特价 - 超大面积 - 含厨房电器 - 停车位',
  'Hot Price | 1 Bedroom Apt | Facilities | Parking | Vacant': '热门价格 | 一室公寓 | 设施 | 停车位 | 空置',
  'Lavish One Bedroom+Hall|Kitchen+Bath|Monthly5300': '奢华一室一厅|厨房+卫浴|月租5300',
  'Low Price | Elegant Finish | Prime Area | Vacant': '低价 | 优雅装修 | 核心区 | 空置',
  'Low Price! | Spacious and Modern Layout | Vacant!': '低价！| 宽敞现代布局 | 空置！',
  'Luxurious Finishing 1Bedroom Monthly 4500 Close Masdar City': '豪华装修一室 月租4500 靠近马斯达尔城',
  'Luxury Finishing One Bed Room Hall With Balcony Separate Kitchen and Bath Tub Wash Room in KCA': '哈利法城A区豪华装修一室一厅 带阳台/独立厨房/带浴缸洗手间',
  'Modern Designed 1 Bedrooom | Ready To Move': '现代设计一室 | 拎包入住',
  'Muroor Area 1 BR Apartment': '穆鲁尔区一室公寓',
  'Offer Today | Bright & Spacious 1Br| Ready to Move': '今日特惠 | 明亮宽敞一室 | 拎包入住',
  'Outstanding Brand New One Bed Room Monthly 4500 Zone 19 MBZ City': '优质全新一室 月租4500 穆罕默德·本·扎耶德城19区',
  'Peaceful Family Compound Proper Amazing 1BHK, Big Kitchen Pvt Balcony, Near Nmc In KCA': '哈利法城A区宁静家庭社区正规优质一室一厅 大厨房/私人阳台 靠近NMC医院',
  'Perfect Location | Stay Connected | Ready for you': '完美地段 | 交通便利 | 随时入住',
  'Priced Right – Bright Comfortable Unit Affordable': '价格合理 – 明亮舒适单位 高性价比',
  'Ready To Move In - Prime Location - No Commission': '拎包入住 - 黄金地段 - 无中介费',
  'Sky Tower View-1BR Apt in Mangrove Place, Reem': '瑞姆岛红树林广场一室公寓 天空塔景观',
  'Square Shaped| Multiple Cheques possible| High FLR': '方正户型 | 可多张支票付款 | 高楼层',
  'Studio with Balcony Tawtheeq Available 0 Bills 0 Commission': '带阳台开间 提供租赁登记 0账单 0中介费',
  'Stunning 1 Bed || Tawtheeq Available || 0 Commission || Free Bills': '惊艳一室 || 提供租赁登记 || 0中介费 || 免账单',
  'Stunning Premium City View | Spacious 1 -Bedroom Apartment': '惊艳高级城市景观 | 宽敞一室公寓',
  'Stunning Tawtheeq Available 0 Commission Free Bill': '极佳房源提供租赁登记 0中介费 免账单',
  'Type C | Unique Living | Peaceful Community': 'C户型 | 独特居住体验 | 宁静社区',
  'Unit Tawtheeq !! 1-Bedroom | American Kitchen | Private Balcony | Share Pool | Basement Parking. .': '房源含租赁登记 !! 一室 | 美式厨房 | 私人阳台 | 共享泳池 | 地下停车位',
  'Unit Tawtheeq !! 1-Bedroom | American Kitchen | Private Balcony | Share Pool | Basement Parking..': '房源含租赁登记 !! 一室 | 美式厨房 | 私人阳台 | 共享泳池 | 地下停车位',
  'Unit Tawtheeq !! Furnished 1Bedroom With Private Balcony / Share Pool / Basement Parking': '房源含租赁登记 !! 带家具一室 配私人阳台 / 共享泳池 / 地下停车位',
  'VACANT ON 1ST APRIL TYPE C 1BR APT PARKING VIEW BOOK NOW': '4月1日空置 C户型一室公寓 停车场景观 立即预订',
  'VACANT ON 1ST APRIL TYPE C 1BR APT W/PARKING VIEW': '4月1日空置 C户型一室公寓 带停车场景观',
  'VACANT | Sea and Amenity View | Up to 2 Payments': '空置 | 海景与设施景观 | 最多可分2次付款',
  'Vacant I Spacious Layout I Prime Location': '空置 | 宽敞布局 | 黄金地段',
  'Vacant On May | Type C | Full Facilities': '5月空置 | C户型 | 设施齐全',
  'Well Maintained 1BR | Gate Tower | Ready to Move In': '维护良好一室 | 门塔 | 拎包入住',
  '√ HOT DEAL! VACANT | Sea View | Prime Location √': '√ 特价！空置 | 海景 | 黄金地段 √',
  // ─── Batch 2026-03-26 (Gemini-translated, 112 titles) ──────
  "01 Bedroom Hall Apartment for Family | Al Rahba": "Al Rahba | 1卧室大厅公寓 | 适合家庭",
  "1 BHK-All Facilities-12 Payments": "1卧室 | 配套齐全 | 12期付款",
  "1 BR Apt Khalidiya Street with View": "Khalidiya Street | 1卧室公寓 | 带景观",
  "1 Bedroom Hall Apartment Villa 2nd floor Opposite Khalidiyah Police St Mnaseer Abu Dhabi": "Abu Dhabi Mnaseer | Khalidiyah Police St 对面 | 别墅二楼 | 1卧室大厅公寓",
  "1BHK Apartment | Pool | Parking": "1卧室公寓 | 泳池 | 停车位",
  "1st Tenant Luxury 1Bedroom+Free WIFI+ Separate Kitchen+ Washroom 4800-Monthly": "首租 | 豪华1卧室+免费WIFI+独立厨房+洗手间 | 月租4800",
  "800 SQFT-PER MONTH 6500-1 BED SIZE SUITE | FURNISH": "800平方英尺 | 月租6500 | 1卧室套房 | 精装",
  "Al Muntazah Studio Apt": "Al Muntazah 单间公寓",
  "Al Muntazah Studio with Security": "Al Muntazah 单间 | 带安保",
  "Al Mushrif 1 BR Apartment FREE ADDC": "Al Mushrif | 1卧室公寓 | 免费水电费 (ADDC)",
  "Al Mushrif Villas Studio Apt": "Al Mushrif Villas | 单间公寓",
  "Amazing Deal! High Floor | UPCOMING UNIT": "超值优惠！高楼层 | 即将上市",
  "Amazing View | Modern Designed 1 BR": "绝美景观 | 现代设计1卧室",
  "BOOK NOW!! AVAILABLE START MAY- TYPE D- 75k ONLY": "立即预订！！5月起可入住 | D型 | 仅7.5万",
  "BRAND NEW ONE BEDROOM IN MBZ ZONE 22": "MBZ ZONE 22 | 全新1卧室",
  "BRAND NEW SPACIOUS 1BHK AVAILABLE IN MBZ ON ZONE 25- close to LULU": "MBZ ZONE 25 | LULU附近 | 全新宽敞1卧室",
  "BRAND NEW SPACIOUS APARTMENT EUROPEAN STYLE 1BHK AVAILABLE IN BANYAS": "BANYAS | 全新宽敞欧式1卧室公寓",
  "BRAND NEW SPACIOUS EUROPEAN STYLE 1BHK AVAILABLE IN BANIYAS": "BANIYAS | 全新宽敞欧式1卧室",
  "BRAND NEW! 1-BEDROOM HALL WITH COVERED PARKING AVAILABLE IN MBZ": "MBZ | 全新！1卧室大厅 | 带顶棚停车位",
  "Best Price| 4 Payments | Prime Location | Book Now": "最优价格 | 4期付款 | 黄金地段 | 立即预订",
  "Brand new-Amazing modern spacious 1/BHK | Sep. kitchen | Ready to move | Parking": "全新-现代宽敞1卧室 | 独立厨房 | 可拎包入住 | 停车位",
  "Brand new-Amazing modern spacious 1/BHK | Sep.kitchen | Ready to move | Parking": "全新-现代宽敞1卧室 | 独立厨房 | 可拎包入住 | 停车位",
  "Brand new|Exclusive|1BHK|Modern|High finishing|Ready to move|Separate kitchen and bathroom": "全新|独家|1卧室|现代|高端装修|可拎包入住|独立厨房和浴室",
  "Captivating 1BR Apt | Balcony with Serene Sea Views | High Floor": "迷人1卧室公寓 | 海景阳台 | 高楼层",
  "City View | 1BHK with Balcony | Vacant Unit": "城市景观 | 1卧室带阳台 | 空置单元",
  "Deluxe Studio with Balcony/ Tenacy Contract/ Direct Owner/ No Agent Fee": "豪华单间 | 带阳台 | 租赁合同 | 业主直租 | 无中介费",
  "EUROPEAN STYLE 1BHK WITH HUGE KITCHEN AND BATHROOM": "欧式1卧室 | 带大厨房和浴室",
  "Excellent One Bhk With Private Entrance At MBZ City": "MBZ City | 绝佳1卧室 | 带独立入口",
  "Exclusive 1BR Apartment  | Elegant Living | Vacant": "独家1卧室公寓 | 优雅生活 | 空置",
  "Exclusive|Brand new|1BHK with backyard|Built in wardrobe|Kitchen and bathroom": "独家|全新|1卧室带后院|内嵌衣柜|厨房和浴室",
  "Exclusive|Brand new|1BHK|Sep-Kitchen and bathroom": "独家|全新|1卧室|独立厨房和浴室",
  "Full Sea View | Layout 06 | Studio with Balcony": "全海景 | 06户型 | 单间带阳台",
  "Fully Furnished 1 Bedroom Apartment With Water & Electricity Included": "全精装1卧室公寓 | 包水电",
  "Fully Furnished!! 1 Bedroom Apartment With Water & Electricity Included": "全精装！！1卧室公寓 | 包水电",
  "Fully Furnished!! Studio Apartment With Water & Electricity Included": "全精装！！单间公寓 | 包水电",
  "Furnished Studio Al Khalidiyah / 5200 Monthly": "Al Khalidiyah 精装单间 | 月租5200",
  "Good Price 1Bhk Apt With Owner Building Big Hall": "好价1卧室公寓 | 业主楼 | 大厅",
  "Good Price | Versatile & Functional Unit | Vacant": "好价 | 多功能实用单元 | 空置",
  "Great Unit | Ready To Move | Flexibile Payments": "绝佳单元 | 随时入住 | 灵活付款",
  "HOT DEAL!!!Stylish 1BR | High Floor | With Balcony": "超值优惠!!!时尚1卧室 | 高楼层 | 带阳台",
  "HOTTEST DEAL!! Excellent View | With Balcony": "最热优惠!! 绝佳视野 | 带阳台",
  "HOTTEST DEAL!! Higher Floor | Ready to Move In": "最热优惠!! 更高楼层 | 随时入住",
  "HOTTEST PRICE!! Splendid 1 BR | High floor": "最热价格!! 华丽1卧室 | 高楼层",
  "High Floor 1BR | Flexible Payment Option | Al Reem": "高楼层1卧室 | 灵活付款选择 | Al Reem",
  "High Floor Apartment | 1BR + Living | Parking": "高楼层公寓 | 1卧室 + 客厅 | 停车位",
  "High Floor | Modern Layout | Prime Location": "高楼层 | 现代布局 | 优越位置",
  "Hot Deal | Spacious View | Moving Ready Now": "热门优惠 | 宽敞视野 | 现可入住",
  "Hot Deal! Studio for Rent | High Floor | Sea View | Balcony": "热门优惠! 单间出租 | 高楼层 | 海景 | 阳台",
  "Hot Offer 1 Bed Hall Apart with Basement Parking": "热门优惠 1卧室大厅公寓带地下停车位",
  "Hot Offer | Iconic 1Bhk | Upto 6 Payments": "热门优惠 | 标志性1卧室 | 最多6期付款",
  "Hot Price | 61k/12cheq | call now | avail it": "热门价格 | 6.1万/12期支票 | 立即致电",
  "LUXURY 1BHK !! ROYAL FINISHING !! SEP KITCHEN !! PROPER WASHROOM !! IN KCA": "豪华1卧室!! 皇家装修!! 独立厨房!! 独立卫生间!! 在KCA",
  "Large Studio+Parking | Flexible Payments | Al Reef": "大单间+停车位 | 灵活付款 | Al Reef",
  "Limited-Time Hot Deal | Canal View Living | Luxury": "限时热门优惠 | 运河景观生活 | 豪华",
  "Low Price | Elegant Finish | Prime Area | Vacant!": "低价 | 优雅装修 | 优越地段 | 空置!",
  "Luxurious|1-BHK|Sep Kitchen|Pool|Parking|Balcony,.": "豪华|1卧室|独立厨房|泳池|停车位|阳台",
  "Luxury 1-bed Flat for rent in Khalifa City Etihad plaza": "Khalifa City Etihad plaza 豪华1卧室公寓出租",
  "Luxury 1-bed Flat in Khalifa City (Etihad plaza)": "Khalifa City (Etihad plaza) 豪华1卧室公寓",
  "Luxury 1-bed flat for rent in Mussafah Gardens": "Mussafah Gardens 豪华1卧室公寓出租",
  "Marvelous Designed 1 BR with Balcony |Amazing VIew": "精心设计1卧室带阳台 | 绝美视野",
  "Modern & Style | Peaceful Community": "现代与时尚 | 宁静社区",
  "Modern Design | 1 Bedroom Apartment | Facilities | Parking": "现代设计 | 1卧室公寓 | 设施 | 停车位",
  "Modern Designed 1 BR with Balcony and Laundry Room": "现代设计1卧室带阳台和洗衣房",
  "Modern Living | Spacious | Up to 4 Payments": "现代生活 | 宽敞 | 最多4期付款",
  "Modern and Elegant Designed 1 BR with Balcony": "现代优雅设计1卧室带阳台",
  "Multiple Payments|Vacant |Prime Location": "多期付款|空置|优越位置",
  "Newly Renovated 1BHK With Parking & Built-In Cupboards": "新装修1卧室带停车位和嵌入式衣柜",
  "One-bedroom annex with a living room, yard, and private entrance. First tenant in Zayed City.": "Zayed City 1卧室附楼带客厅、院子和独立入口 首租",
  "One-bedroom apartment with living room, first occupancy in Shakhbout City, prime location": "Shakhbout City 1卧室公寓带客厅 首次入住 优越位置",
  "Partial Canal View | VACANT | Up to 4 Payments": "部分运河景观 | 空置 | 最多4期付款",
  "Premium Furnished Apartment for Rent – First Tenant 📍 Khalifa City A | Excellent Location near Al Safeer Mall": "Khalifa City A 优质精装公寓出租 首租 | 靠近Al Safeer Mall",
  "Prime Area | Canal View Living | Bright & Spacious": "优越地段 | 运河景观生活 | 明亮宽敞",
  "Pvt. Balcony-Modern spacious 1/BHK | Elevator | Sep. kitchen | Modern bath | Parking": "私人阳台-现代宽敞1卧室 | 电梯 | 独立厨房 | 现代浴室 | 停车位",
  "Pvt.Balcony-Modern spacious 1/BHK | Elevator | Sep.kitchen | Modern bath | Parking": "私人阳台-现代宽敞1卧室 | 电梯 | 独立厨房 | 现代浴室 | 停车位",
  "RARE Availability! Upcoming | Facing the Community": "稀有供应! 即将推出 | 面向社区",
  "Ready to Move-in | Dazzling 1BR | Top Community": "随时入住 | 耀眼1卧室 | 顶级社区",
  "Reserve Now Studio with Tawtheeq 0 Commission Free Bills": "立即预订单间 | 含Tawtheeq 0佣金免账单",
  "Reserve Now Tawtheeq Avail 0 Commission Free Bills": "立即预订 | Tawtheeq可用 0佣金免账单",
  "SPACIOUS 1 BED | 4 PAYMENTS | GYM POOL | CHILLER FREE": "宽敞1卧室 | 4期付款 | 健身房泳池 | 免冷却费",
  "Sea View Furnished Spacious Studio | Ready to Move": "海景精装宽敞单间 | 随时入住",
  "Sea View | Mid Floor | Vacant | Prime Location": "海景 | 中层 | 空置 | 黄金地段",
  "Sea View | Spacious Layout | Ready to move in": "海景 | 宽敞布局 | 随时入住",
  "Secure Now Tawtheeq Avail Free Bills 0 Commission": "立即锁定 | Tawtheeq可用 免账单 0佣金",
  "Spacious 1 BHK Apartment | Balcony | Parking": "宽敞1卧室公寓 | 阳台 | 停车位",
  "Spacious 1BR Apartment | Burooj Views |": "宽敞1卧室公寓 | Burooj景观",
  "Spacious 1BR Apt | Partial Sea and Community View | Vacant Soon": "宽敞1卧室公寓 | 部分海景和社区景观 | 即将空置",
  "Spacious 1BR | Modern Living | Ready to Move": "宽敞1卧室 | 现代生活 | 随时入住",
  "Spacious Tawtheeq Available 0 Commission Free Bill": "宽敞 | Tawtheeq可用 0佣金免账单",
  "Spacious Unit || Vacant || Contact ASAP ||": "宽敞单元 | 空置 | 尽快联系",
  "Spacious ~ Prime location ~ Ready to move": "宽敞 ~ 黄金地段 ~ 随时入住",
  "Special Offer 18 March - 1BR| Sea View | Ready Now": "特价优惠 3月18日 - 1卧室| 海景 | 立即入住",
  "Specious 1 Bedrooms + Living Room Apartment Near Dalma Mall": "宽敞1卧室+客厅公寓 靠近Dalma Mall",
  "Stunning 1BR APT | Prime Location | Ready to Move": "惊艳1卧室公寓 | 黄金地段 | 随时入住",
  "Stunning 2BR | Elegant Layout | Best Location": "惊艳2卧室 | 优雅布局 | 最佳地段",
  "Stylish 1 BHK | Pool, Gym & Kids Play": "时尚1卧室 | 泳池、健身房和儿童游乐区",
  "Suite Furnished Rooms | Al Reem Island | Wave tower | 5,500 AED Monthly": "套房精装房间 | Al Reem Island | Wave tower | 月租5500迪拉姆",
  "Suite Room in Al Reem-Wave tower 5,500 AED Monthly": "Al Reem-Wave tower 套房 月租5500迪拉姆",
  "Sunny Modern Family Home with Spacious Layout": "阳光充足的现代家庭住宅 宽敞布局",
  "Type C 1BR| Ready To Occupy| Big Layout| Book Now": "C型1卧室 | 即可入住 | 大户型 | 立即预订",
  "Type C | Big Layout | Peaceful Community": "C型 | 大户型 | 宁静社区",
  "ULTRA MODERN 1 BHK | BALCONY with POOL VIEW | FITTED KITCHEN |TOP TIER FACILITIES |2 PYAMENTS PARKING and more!": "超现代1卧室 | 带泳池景观阳台 | 配套厨房 | 顶级设施 | 2期付款停车位等",
  "Upcoming, Book Now, Waterfront Living, 1 Master Bedroom": "即将推出 立即预订 海滨生活 1主卧室",
  "VACANT HOT DEAL TYPE C 1BR APT W/BUILDING VIEW": "空置热门优惠 C型1卧室公寓 带建筑景观",
  "Vacant 1BR | Amazing Community | Ideal Location": "空置1卧室 | 绝佳社区 | 理想地段",
  "Vacant | High Level Unit Overlooking the Pool": "空置 | 俯瞰泳池高层单元",
  "Vacant | Partial Sea View | Easy Payment Available": "空置 | 部分海景 | 轻松付款可用",
  "Vacant | Prime Locations | Top Facilities": "空置 | 黄金地段 | 顶级设施",
  "Vacant | Spacious Unit  | Prime Location": "空置 | 宽敞单元 | 黄金地段",
  "Well-Maintained 1BR | Sea View | Ready to Move": "保养良好1卧室 | 海景 | 随时入住",
  "| 1 Bedroom | Canal View | Spacious | Prime Location | Vacant |": "| 1卧室 | 运河景观 | 宽敞 | 黄金地段 | 空置 |",
  "⇨Sea View ⇨With Balcony ⇨Ready To Move ⇨HOT DEAL": "海景 | 带阳台 | 随时入住 | 热门优惠",
  "√High Floor | Up to 4 Payments | Prime Location√": "高层 | 最多4期付款 | 黄金地段",
  // ─── Batch 2026-03-30 (Gemini-translated, 52 titles) ──────
  "Stunning 1BHK ! Ready To Move ! Inquire Now": "惊艳一居室！即可入住！立即咨询",
  "Vacant Now | Luxury View Living | Sea View Full": "现房空置 | 奢华景观生活 | 全海景",
  "NICE ONE BEDROOM HALL APARTMENT AVAILABLE IN KHALIDIYA BACKSIDE SHERATON HOTEL READY TO MOVE": "Khalidiya喜来登酒店背面一卧室带厅公寓，即可入住",
  "HOT DEAL!! Excellent View | Without Balcony": "热销优惠！绝佳视野 | 无阳台",
  "Spacious 1BR+Store | Flexible Payments | Al Reef": "宽敞一卧室+储藏室 | 灵活付款 | Al Reef",
  "European Society Style One Bedroom Hall With Separate Kitchen Big Sunlight Windows Proper Bath KCA": "欧式风格一卧室带厅，独立厨房，大采光窗户，KCA舒适浴室",
  "Iconic view l 1 Bedroom Apt | Balcony | Facilities | Parking": "标志性景观 | 一卧室公寓 | 阳台 | 设施 | 停车位",
  "Vacant | Modern Living | Full Facilities": "空置 | 现代生活 | 设施齐全",
  "Furnished Studio Julphar Residence | 6,200 monthly": "Julphar Residence带家具单间公寓 | 月租6,200",
  "1 BR Apartment l Vacant l Open View": "一卧室公寓 | 空置 | 开阔视野",
  "SEA VIEW | Vacant Now | Up to 3 Payments | Balcony": "海景 | 现房空置 | 最多3期付款 | 阳台",
  "HOT DEAL!! 3 Cheques | Fantastic View | Furnished": "热销优惠！3期付款 | 绝美视野 | 带家具",
  "SPACIOUS 1 BR || MODERN LUXURY LIVING || READY TO MOVE IN": "宽敞一卧室 || 现代奢华生活 || 即可入住",
  "1 BHK apartment for rent in Corniche area, Al Khalidiya - Al Jimi Avenue - AED 68000": "Al Khalidiya - Al Jimi Avenue滨海区一居室公寓出租 - 68000迪拉姆",
  "Iconic View | 1 Bedroom Apartment | Facilities | Parking": "标志性景观 | 一卧室公寓 | 设施 | 停车位",
  "1BR + Balcony | Un-Furnished | Iconic Views": "一卧室+阳台 | 不带家具 | 标志性景观",
  "HOT DEAL!! 85K/4 | Higher Floor | With Balcony": "热销优惠！8.5万/4期付款 | 高楼层 | 带阳台",
  "Upcoming One-Bedroom || Prime Location||Direct Owner": "即将推出一卧室 || 黄金地段 || 业主直租/售",
  "Large 1Bhk Apt With 2 Bathroom Big Hall Owner Building": "两卫大厅大一居室公寓，业主大楼",
  "Vacant | Ready To Move | With Balcony | Book Now": "空置 | 即可入住 | 带阳台 | 立即预订",
  "Balcony | Ready To Move | Prime Location": "阳台 | 即可入住 | 黄金地段",
  "Hot Deal | Prime Location | Ready To Move": "热销 | 黄金地段 | 即可入住",
  "Vacant Now | Sea View Living | Prime Location": "现房空置 | 海景生活 | 黄金地段",
  "Type A | Vacant Unit | Perfect Community": "A户型 | 空置单位 | 完美社区",
  "2 Payment |Vacant |Furnished 1BR+Balcony|Pool View": "2期付款 | 空置 | 带家具一卧室+阳台 | 泳池景观",
  "Vacant | 2 Payments | High Floor | 1BR + Balcony": "空置 | 2期付款 | 高楼层 | 一卧室+阳台",
  "Spacious -1BHK-Prime Location": "宽敞一居室 - 黄金地段",
  "556 sqft |Furnished | Multiple Instalments| Vacant": "556平方英尺 | 带家具 | 多期付款 | 空置",
  "Vacant soon / Balcony / Hot Deal": "即将空置 / 阳台 / 热销优惠",
  "BRAND NEW 1BHK AVAILABLE IN SHABIYA 09 WITH TAWTEEQ AND PARKING (ONLY ASIANS )": "Shabiya 09全新一居室，带Tawteeq和停车位（仅限亚洲人）",
  "12 Payments | Hot Offer | 1Bhk+Balcony": "12期付款 | 热门优惠 | 一居室+阳台",
  "Amazing View / 1 BR Apartment": "绝美视野 / 一卧室公寓",
  "Luxury Studio  | Furnished | Sea View | Vacant": "豪华单间公寓 | 带家具 | 海景 | 空置",
  "Al Falah Street 1 BR Apartment": "Al Falah街一卧室公寓",
  "⁂ Elite Community⁂ Prime Location ⁂Ready To Move ⁂": "⁂ 精英社区 ⁂ 黄金地段 ⁂ 即可入住 ⁂",
  "1BR+Balcony | Flexible payment | Marina view": "一卧室+阳台 | 灵活付款 | 码头景观",
  "Executive Studio Apartment | Parking | Amenities": "行政单间公寓 | 停车位 | 便利设施",
  "ULTRA MODERN 1 BHK | BALCONY with POOL VIEW | FITTED KITCHEN |TOP TIER FACILITIES |2 PYAMENTS PARKING | ENQUIRE TODAY!": "超现代一居室 | 泳池景观阳台 | 配套厨房 | 顶级设施 | 2期付款停车位 | 今日咨询！",
  "Modern 1BHK Balcony Gym Parking Shams Meera Reem": "现代一居室，阳台，健身房，停车位，Shams Meera Reem",
  "RENOVATION STUDIO APARTMENT AVAILABLE NEAR MUSHRIF MALL": "Mushrif Mall附近有翻新单间公寓",
  "Vacant 1BR | Stunning Sea View | Elevated Floor": "空置一卧室 | 惊艳海景 | 高楼层",
  "Furnished | Up to 3 Payments | Ready to Move": "带家具 | 最多3期付款 | 即可入住",
  "SEA VIEW! Vacant Now | Up to 3 Payments | Balcony": "海景！现房空置 | 最多3期付款 | 阳台",
  "Huge Layout| Natural Light| Easy installments": "超大格局 | 自然采光 | 轻松分期付款",
  "Specious 1 BHK Apartment | Balcony | Parking": "宽敞一居室公寓 | 阳台 | 停车位",
  "Ready To Move | Prime Location | flexible payment": "即可入住 | 黄金地段 | 灵活付款",
  "Khalifa City A Villas 1 BR Apartment": "Khalifa City A别墅区一卧室公寓",
  "NEW SPACIOUS 1BHK AVAILABLE IN SHABIYA WITH TAWTEEQ AND PARKING INCLUDING (ASIANS ONLY )": "Shabiya全新宽敞一居室，带Tawteeq和停车位（仅限亚洲人）",
  "HOTTEST PRICE!! Splendid 1BR | High floor": "超低价！！绝佳一卧室 | 高楼层",
  "Splendid | 1 Bedroom Apt | Facilities | Parking | Vacant": "绝佳 | 一卧室公寓 | 设施 | 停车位 | 空置",
  "Ready To Move || Prime Location || Tawtheeq Available || Direct Owner ||": "即可入住 || 黄金地段 || 可办Tawtheeq || 业主直租/售 ||",
  "Prime Location | Bright & Spacious | Great View": "黄金地段 | 明亮宽敞 | 视野极佳",
  "1BHK W/2 Bathrooms | BRAND NEW | No Commission!": "一居室两卫 | 全新 | 无中介费！",
  "1BHK W/2 Bathrooms | Free ADDC | No Commission": "一居室两卫 | 免费水电 | 无中介费",
  "1BHK W/2 Bathrooms | Free ADDC | No Commission!": "一居室两卫 | 免费水电 | 无中介费！",
  "AMAZING DEAL!! Spacious 1 BR | From MARCH 27": "超值优惠！！宽敞一居室 | 3月27日起可入住",
  "Amazing 1BR- Kitchen Appliances - 4payments": "精品一居室 | 带厨房电器 | 四期付款",
  "Amazing Unit | Best Rental Value | Flexible Option": "优质房源 | 高性价比 | 灵活选择",
  "BIG 1 BED + TWO WASHROOMS | 4 PAYMENTS | GYM POOL": "宽敞一居室两卫 | 四期付款 | 健身房泳池",
  "BOOK NOW!! AVAILABLE 1st APRIL-80K UPTO 4 PAYMENTS": "立即预订！！4月1日起可入住 - 8万（四期付款）",
  "BOOK NOW!! AVAILABLE MID APRIL- TYPE C- 75K ONLY": "立即预订！！4月中旬可入住 - C型 - 仅7.5万",
  "BOOK NOW!!! AVAILABLE 9th MAY- SEA VIEW 80000 ONLY": "立即预订！！！5月9日起可入住 - 海景 - 仅8万",
  "BRAND NEW 1 BEDROOM HALL 2 BATHROOM APARTMENT WITH SEPARATE ENTRANCE": "全新一居室两卫 | 独立入口公寓",
  "Balcony | Marina View | Upcoming 17th April": "阳台 | 码头景观 | 4月17日可入住",
  "Balcony | Negotiable Price | Upcoming April 17": "阳台 | 价格可议 | 4月17日可入住",
  "Beach Access | Upgraded | Biggest Layout !!": "近海滩 | 豪华装修 | 最大户型！！",
  "Brand New 1BHK Apt 2 Bathroom With Basement parking Wardrobe Balcony": "全新一居室两卫公寓 | 带地下停车位、衣柜、阳台",
  "Brand New 1BHK W/2Bathroom | No Commission | Free ADDC": "全新一居室两卫 | 无中介费 | 免费水电",
  "Corner 1BR+Store | Flexible Payments | AL Reef": "角落一居室带储藏室 | 付款灵活 | 丽夫社区",
  "Cozy Unit | High Floor | Ready To Move": "舒适房源 | 高楼层 | 拎包入住",
  "Elegant 1BHK Apartment | Spacious Layout | 2 Bathrooms | Ready to Move": "雅致一居室公寓 | 宽敞户型 | 两卫 | 拎包入住",
  "Furnished Suite Alreem Island, 4999/- Monthly": "丽姆岛精装套房 | 月租4999迪拉姆",
  "HOT DEAL!! 85K/4 | High Floor | With Balcony": "超值优惠！！8.5万/四期 | 高楼层 | 带阳台",
  "HOTTEST DEAL!! Four Cheques | Amazing View": "最热优惠！！四期付款 | 绝佳景观",
  "High Floor 1BR+Balcony|Mangrove View| 3 Payment": "高楼层一居室带阳台 | 红树林景观 | 三期付款",
  "High Floor l Amazing View l Vacant": "高楼层 | 绝佳景观 | 空置",
  "Hot Deal Sea View Ready To Move Peaceful Community": "超值海景房 | 拎包入住 | 宁静社区",
  "Hot Deal | Luxurious Apartment | Basement Parking | Ready to Move": "超值优惠 | 豪华公寓 | 地下停车位 | 拎包入住",
  "Hot Deal! Sea View Studio for Rent | Balcony | Best Price": "超值优惠！海景单间公寓出租 | 带阳台 | 最优价格",
  "Iconic view | 1 Bedroom Apt | Balcony | Facilities | Parking": "标志性景观 | 一居室公寓 | 阳台 | 配套设施 | 停车位",
  "LIMIT TIME OFFER | 1BHK VIEW | ALL AMENTIES": "限时优惠 | 一居室景观房 | 配套齐全",
  "Luxurious Fully Furnished Studio for Rent Book Now": "豪华精装单间公寓出租 | 立即预订",
  "Marvelous Designed 1 BR with Balcony and Laudnry Room": "精心设计一居室 | 带阳台和洗衣房",
  "Modern Layout | Ready to Move In | Prime Location": "现代布局 | 拎包入住 | 优越地段",
  "Modern Living | Spacious | Prime Community": "现代生活 | 宽敞 | 优质社区",
  "Premium Facilities | huge balcony | sea view": "高端设施 | 超大阳台 | 海景",
  "Prime Location || Tawtheeq Available || Direct Owner || Bills included": "优越地段 || 可办理Tawtheeq || 房东直租 || 包水电费",
  "Ready To Move | Prime Location | Flexible payment": "拎包入住 | 优越地段 | 付款灵活",
  "Relaxing View | Well Maintained |Move in Ready": "休闲景观 | 维护良好 | 拎包入住",
  "SPACIOUS 1 MASTER BEDROOM APARTMENT IN SHABIYA 9.": "沙比亚9区宽敞一居室公寓",
  "SPACIOUS! 1-BEDROOM HALL AT GROUND FLOOR IN MBZ": "MBZ区宽敞一居室公寓（首层）",
  "Sea View | Spacious Community | Moving Ready": "海景 | 宽敞社区 | 拎包入住",
  "Sea View | Upcoming 6th April | Prime Location": "海景 | 4月6日可入住 | 优越地段",
  "Sea View | Upcoming 6th April | Ready To Move": "海景 | 4月6日可入住 | 拎包入住",
  "Separate Entrance Tawtheeq Available 0 Commission Free Bills": "独立入口 | 可办理Tawtheeq | 无中介费 | 免费账单",
  "Spacious 1 Bedroom Apartment for Rent in Musaffah Shabiya 10": "穆萨法沙比亚10区宽敞一居室公寓出租",
  "Spacious 1BHK Apartment for Rent in Shabiya (10/11/12/9)": "沙比亚（10/11/12/9区）宽敞一居室公寓出租",
  "Spacious 1BR -Parking-4payments-Kitchen Appliances": "宽敞一居室 | 停车位 | 四期付款 | 厨房电器",
  "Spacious Studio Tawtheeq Available 0 Bills 0 Commission": "宽敞单间公寓 | 可办理Tawtheeq | 免费账单 | 无中介费",
  "ULTRA MODERN 1 BHK | BALCONY with POOL VIEW | FITTED KITCHEN |TOP TIER FACILITIES |2 PYAMENTS PARKING | CALL US & ENQUIRE TODAY!!!!": "超现代一居室 | 泳池景观阳台 | 配套厨房 | 顶级设施 | 两期付款带停车位 | 立即咨询！！！！",
  "Unfurnished-1BHK+Laundry-Prime Location": "无家具一居室带洗衣房 | 优越地段",
  "Vacant Soon | Book Now | Ideal Community": "即将空置 | 立即预订 | 理想社区",
  "Vacant|Stunning 1BR|Stylish Layout|Modern Living": "空置 | 惊艳一居室 | 时尚布局 | 现代生活",
  "Water View-1BR Apt in Mangrove Place, Reem": "丽姆岛红树林公寓水景一居室",
  "pvt entrance high finishing newly 1 B/R hall with separate kitchen": "独立入口 | 高品质新装修一居室带独立厨房",

  // ─── 2026-04-20 supplementary translations ───
  "1 BHK | Move-In Ready| Parking": "1居 | 即可入住 | 带车位",
  "1 Bedroom Type A | Spacious layout | Available": "1居 A户型 | 宽敞布局 | 可入住",
  "1 bedroom Apartment for Rent AED 70k ready to move in": "1居公寓出租 70k AED 即可入住",
  "12 Cheque  STUDIO   Furnished   Balkony +pool +Gym": "12张支票付清 开间 带家具 阳台 + 泳池 + 健身房",
  "1BHK Apartment with Balcony & Basement Parking": "1居公寓 带阳台 & 地下停车位",
  "1BHK Apartment with Balcony & Basement Parking | Shabiya 9, 10, 11 & 12 | Chiller Free": "1居公寓 带阳台 & 地下停车位 | Shabiya 9、10、11 & 12 | 免空调费",
  "1BHK/2 Washroom/Parking/Owner Property/Shabiya 12": "1居 / 2卫 / 停车位 / 业主房源 / Shabiya 12",
  "1BR + Balcony | Gate Tower View | Spacious Unit": "1居 + 阳台 | Gate Tower 景观 | 宽敞户型",
  "1BR High Floor | Sea View | Balcony | Parking": "1居高层 | 海景 | 带阳台 | 带车位",
  "1BR With Balcony | Modern Layout| Vacant soon": "1居带阳台 | 现代布局 | 即将空置",
  "1Bedroom | Spacious Apartment | Available For Rent": "1居 | 宽敞公寓 | 可出租",
  "2 Payment|Luxury Furnished Studio|Sea View|Vacant": "2期付款 | 豪华精装开间 | 海景 | 空置",
  "Affordable Studio | Flexible Payments | Al Reem": "实惠开间 | 灵活付款 | Al Reem",
  "Al Muntazah Studio Apartment": "Al Muntazah 开间公寓",
  "Al Mushrif Villas Apt 1 BR": "Al Mushrif Villas 1居公寓",
  "Al Mushrif Villas Studio with Balcony": "Al Mushrif Villas 带阳台开间",
  "Alluring 1BHK With Water & Electricity Included": "迷人 1居 含水电",
  "Alluring Marina Bay View | Vacant | Modern Area": "迷人 Marina Bay 景观 | 空置 | 现代社区",
  "Amazing Location | Sea View | Available Now": "绝佳地段 | 海景 | 即可入住",
  "Amazing One Bed Room with Balcony in MBZ City": "MBZ City 带阳台 1居精品房源",
  "Amazing View l Hot Deal l Ready To Move In": "迷人景观 l 超值房源 l 即可入住",
  "Amazing | Brand new | Modern spacious 1/BHK+2bath | Sep. kitchen | Modern bath | Parking": "精品 | 全新 | 现代宽敞 1居 + 2卫 | 独立厨房 | 现代浴室 | 带车位",
  "Amazing | Brand new | Modern spacious 1/BHK+2bath | Sep.kitchen | Modern bath | Parking": "精品 | 全新 | 现代宽敞 1居 + 2卫 | 独立厨房 | 现代浴室 | 带车位",
  "BEST PRICE!! Three Payments | Excellent 1 BR": "最佳价格！！3期付款 | 优质 1居",
  "BRAND NEW! 1-BEDROOM HALL WITH SEPARATE ENTERANCE WITH COVERED PARKING AVAILABLE IN MBZ": "全新！1居带客厅 独立入口 带顶棚车位 位于 MBZ",
  "Balcony | High Floor | Prime Location": "带阳台 | 高层 | 黄金地段",
  "Balcony | High Floor | Ready to Move": "带阳台 | 高层 | 即可入住",
  "Balcony | High Floor | Vacant | Hot Price": "带阳台 | 高层 | 空置 | 超值价格",
  "Balcony | Marina View | Ready To Move": "带阳台 | Marina 景观 | 即可入住",
  "Balcony | Negotiable Price | Ready To Move": "带阳台 | 价格可议 | 即可入住",
  "Balcony | Partial Marina View | Ready to Move": "带阳台 | 侧面 Marina 景观 | 即可入住",
  "Best Choice | Luxury Living | Call Now": "最佳选择 | 奢华生活 | 立即致电",
  "Best Deal 1BR | Marina Bay DAMAC | Al Reem Island": "超值 1居 | Marina Bay DAMAC | Al Reem Island",
  "Best Deal | Studio for Rent | Prime Location": "超值 | 开间出租 | 黄金地段",
  "Best Layout ⇛With Balcony ⇛Prime Location": "最佳户型 ⇛ 带阳台 ⇛ 黄金地段",
  "Best Price  -Huge Layout| Easy installments": "最佳价格 - 超大户型 | 灵活分期",
  "Big Balcony | Utilities Included | Zero Commission": "大阳台 | 含水电 | 零佣金",
  "Biggest Layout | Modern Living | Book Now": "最大户型 | 现代生活 | 立即预订",
  "Brand New 1BR I Chiller Free I Ready to move in": "全新 1居 I 免空调费 I 即可入住",
  "Brand new 1BR I 1 Parking I Ready to Move in I chiller free": "全新 1居 I 1车位 I 即可入住 I 免空调费",
  "Brand new-Pvt backyard | Modern 1/BHK | Sep. kitchen | Modern bath": "全新 - 私家后院 | 现代 1居 | 独立厨房 | 现代浴室",
  "Brand new-Pvt backyard | Modern 1/BHK | Sep.kitchen | Modern bath": "全新 - 私家后院 | 现代 1居 | 独立厨房 | 现代浴室",
  "Brand new|Modern|Hig finishing|Exclusive|1BHK|Ready to move|Sep. kitchen and bathroom": "全新 | 现代 | 高级装修 | 尊享 | 1居 | 即可入住 | 独立厨卫",
  "Brand new|Modern|Hig finishing|Exclusive|1BHK|Ready to move|Sep.kitchen and bathroom": "全新 | 现代 | 高级装修 | 尊享 | 1居 | 即可入住 | 独立厨卫",
  "C-1 Najmat 1 BR Apartment | Amenities": "C-1 Najmat 1居公寓 | 配套齐全",
  "Canal View | 1-month Free | Ready to move": "运河景 | 免1个月 | 即可入住",
  "Canal View|  1BHK With Balcony| Ready to Move in": "运河景 | 1居带阳台 | 即可入住",
  "Canal View| Amazing 1BHK With Balcony| Ready to Move in": "运河景 | 精品 1居带阳台 | 即可入住",
  "Common Terrace 0 Commission 0 Bills Tawtheeq Avail": "公共露台 零佣金 零账单 已备案",
  "Corner Studio Vacant | Flexible Payments | Al Reem": "转角开间 空置 | 灵活付款 | Al Reem",
  "Cozy Studio ||Tawtheeq Available || Bills Included": "温馨开间 | 已备案 | 含水电",
  "Deluxe 1 Bed Tawtheeq Available 0 Bills 0 Commission": "豪华 1居 已备案 零账单 零佣金",
  "Elegant 1 Bedroom Apt | Facilities | Parking | Ready to Move": "优雅 1居公寓 | 配套齐全 | 带车位 | 即可入住",
  "Elegant 1BHK with Balcony | 2 Baths | Newly Built Residence": "优雅 1居带阳台 | 2卫 | 新建住宅",
  "Elegant Apartment | Balcony Living | Bright & Spacious": "优雅公寓 | 阳台生活 | 明亮宽敞",
  "Elegant Apartment | Modern Layout | Prime Location": "优雅公寓 | 现代布局 | 黄金地段",
  "Elegant Designed 1 BR with Balcony and Basement Parking": "优雅设计 1居 带阳台和地下停车位",
  "Elegant designed 1 BR with Balcony": "优雅设计 1居 带阳台",
  "Elegant | 1 Bedroom Apt | High Floor | Facilities | Parking": "优雅 | 1居公寓 | 高层 | 配套齐全 | 带车位",
  "Elite Unit | Waterfront Living |12 Payments": "精英户型 | 滨水生活 | 12期付款",
  "European Compound Big 1 BHK Unfurnished with Separate Big Kitchen and Bath 52k Yearly": "欧式社区大1居 不带家具 带独立大厨房及浴室 年租 52k",
  "European Luxury 1Bedroom+Pvt Entrance+Kitchen 4800": "欧式豪华 1居 + 私人入口 + 厨房 4800",
  "European Luxury 1Bedroom+WIFI+Kitchen=Bath 4800-M": "欧式豪华 1居 + WIFI + 厨房 + 浴室 每月 4800",
  "European Society Style 1BHK With Separate Kitchen Big Sunlight Windows Proper Bath KCA": "欧式风格 1居 带独立厨房 大阳光窗 标准浴室 KCA",
  "European Style Big 1 BHK Unfurnished with Sunny Windows American Kitchen Shared Terrace 4800 Monthly": "欧式风格大 1居 不带家具 带阳光窗 美式厨房 共用露台 每月 4800",
  "European style 1Bedroom+Pvt Balcony +Kitchen +Bath": "欧式 1居 + 私人阳台 + 厨房 + 浴室",
  "Executive Studio Apartment | Balcony | Amenities": "行政开间公寓 | 带阳台 | 配套齐全",
  "First Floor | Spacious Yard | Open Kitchen | Good Price": "1楼 | 宽敞庭院 | 开放式厨房 | 优惠价格",
  "Flexible Payment • High Floor • Sea View": "付款灵活 • 高层 • 海景",
  "Flexible Payments | Balcony | Ready to Move": "灵活付款 | 带阳台 | 即可入住",
  "Full Sea View-1BHK-Kitchen Appliances": "全海景 - 1居 - 带厨房电器",
  "Fully Furnished | Easy Access to ADGM | 1 Bedroom": "家具齐全 | 便达 ADGM | 1居",
  "Fully Furnished | Ready to Move | Vacant Now": "家具齐全 | 即可入住 | 现已空置",
  "Furnished Studio Al Khalidiyah / 4800 Monthly": "带家具开间 Al Khalidiyah / 每月 4800",
  "Furnished Studio In Alreem Island, Marina Heights": "带家具开间 位于 Al Reem Island, Marina Heights",
  "Furnished Studio with balcony | 4800 Monthly": "带家具开间 带阳台 | 每月 4800",
  "Furnished suite room Al Reem Island/ 4500 Monthly": "带家具套房 Al Reem Island / 每月 4500",
  "Furnished|1-BHK|Sep Kitchen|Pool|Parking|Balcony,.": "带家具 | 1居 | 独立厨房 | 泳池 | 车位 | 阳台",
  "HOT DEAL VACANT 1BR APT MODERN LIVING READY TO MOVE": "超值房源 空置 1居公寓 现代生活 即可入住",
  "HOT DEAL VACANT 1BR MODERN LIVING READY TO MOVE": "超值房源 空置 1居 现代生活 即可入住",
  "HOT DEAL | FURNISHED STUDIO | ARC TOWER for RENT": "超值房源 | 带家具开间 | ARC TOWER 出租",
  "HOT DEAL! New Building | Spacious 1BHK | Balcony": "超值！新楼 | 宽敞 1居 | 带阳台",
  "HOT DEAL!! With balcony | Four Cheques": "超值！！带阳台 | 4张支票付清",
  "HOT Deal | Full Sea View | With Balcony | Vacant !": "超值房源 | 全海景 | 带阳台 | 空置！",
  "HOT OFFER | CLOSED KITCHEN | READY APARTMENT": "特惠 | 封闭式厨房 | 现房公寓",
  "HOT OFFER | STUDIO+CABINET and POOL. GYM, CAR-PARK": "特惠 | 开间 + 储物柜 泳池 健身房 车位",
  "High Floor | Scenic View | Vacant | 3 Easy Payment": "高层 | 风景秀丽 | 空置 | 3期轻松付款",
  "High Floor | Vacant Soon | Sea View": "高层 | 即将空置 | 海景",
  "High ROI | Spacious 1BR | Tranquil Community View": "高收益 | 宽敞 1居 | 静谧社区景观",
  "High-Floor Unit in Marina | Hot Deal Today!": "Marina 高层户型 | 今日特惠！",
  "Hot Deal / Vacant / Ready to move": "超值 / 空置 / 即可入住",
  "Hot Deal | Best View Unit | Vacant | Mid Floor": "超值房源 | 最佳景观户型 | 空置 | 中层",
  "Hot Deal | Marvelous Designed 1 BR with Balcony": "超值房源 | 设计精美 1居 带阳台",
  "Hot Deal | Ready to Move In | 2 Payments": "超值房源 | 即可入住 | 2期付款",
  "Hot Deal | Stunning Canal View | High Floor": "超值房源 | 迷人运河景 | 高层",
  "Hot Deal | Vacant Soon | Furnished | Marina View": "超值房源 | 即将空置 | 带家具 | Marina 景观",
  "Hot Deal! Spacious 1BHK with 2 Washrooms | Ready to Move": "超值！宽敞 1居 带2卫 | 即可入住",
  "Hot Offer | Chiller Free | New Building | Ready To Move": "特惠 | 免空调费 | 新楼 | 即可入住",
  "Hot Offer | New Building | Sea View | Huge & Bright": "特惠 | 新楼 | 海景 | 宽敞明亮",
  "Hot Price | 61k/3cheq | FURNISHED | call now | avail it": "超值价格 | 61k / 3张支票 | 带家具 | 立即致电 | 把握机会",
  "Hot Price | Prime Al Reem Address | Ready for You": "超值价格 | Al Reem 黄金地址 | 静候入住",
  "Huge Studio Apt in Hydra Avenue, Reem Island": "超大开间公寓 位于 Reem Island, Hydra Avenue",
  "LAST OFFER!! HIGHFLOOR | FLEXIBLE PAYMENTS": "最后机会！！高层 | 灵活付款",
  "Large 1BR | Type C | Spacious Layout | Al Reef": "大 1居 | C户型 | 宽敞布局 | Al Reef",
  "Luxurious|Brand new|1BHK |Sep-Kitchen and bathroom": "奢华 | 全新 | 1居 | 独立厨卫",
  "Luxury Furnished 1Bedroom+Kitchen=Bath 5200-M KCA": "豪华带家具 1居 + 厨房 + 浴室 每月 5200 KCA",
  "Luxury Hot Deal Great Facilities Ready To Move": "奢华超值房源 优质设施 即可入住",
  "MODERN N CHIC| BALCONY| GYM POOL PARKING| CALL NOW": "现代时尚 | 带阳台 | 健身房 泳池 车位 | 立即致电",
  "Mangrove & Sea View | High Floor | Big Layout": "红树林 & 海景 | 高层 | 大户型",
  "Marvelous l 1 Bedroom with Balcony l Amenities": "精品 l 1居带阳台 l 配套齐全",
  "Modern 1 Bedroom Flat | Equipped Kitchen & Parking | AED 60K": "现代 1居公寓 | 配套厨房 & 车位 | 60K AED",
  "Modern 1BHK | Free ADDC | No Commission | Hot Deal": "现代 1居 | 免 ADDC | 零佣金 | 超值房源",
  "Modern 1BHK | Free ADDC | No Commission | Hot Deal.": "现代 1居 | 免 ADDC | 零佣金 | 超值房源",
  "Modern Lifestyle| Water View| Available soon": "现代生活方式 | 水景 | 即将上市",
  "Modern Living | Your Next Home Awaits | Book Now": "现代生活 | 您的下一个家在此 | 立即预订",
  "Modern Studio| Prime Location| Ready To Move": "现代开间 | 黄金地段 | 即可入住",
  "Modern Waterfront Living | 1 Bed + Storage & Huge Balcony": "现代滨水生活 | 1居 + 储藏室 & 大阳台",
  "Moving Ready | Well-Appointed Home | Prime Area": "即可入住 | 装修精良家园 | 黄金地段",
  "Newly Renovated 1 Bed with Sea View | Available Now!": "全新装修 1居 带海景 | 即可入住！",
  "One bedroom apartment with living room in Shakhbout City, prime location.": "1居公寓带客厅 位于 Shakhbout City 黄金地段",
  "PRIME LOCATION 1 BHK+CABINET and POOL,GYM CAR PARK": "黄金地段 1居 + 储物柜 泳池、健身房、车位",
  "PRIME LOCATION | STUDIO w/ CABINET and POOL.GYM, CAR PARKING": "黄金地段 | 开间 带储物柜 泳池、健身房、车位",
  "PRIME LOCATION/INCLUDING BILLS/NO COMMISSION": "黄金地段 / 含水电 / 零佣金",
  "PRIME LOCATION/PARKING FREE/ NO COMMISSIN": "黄金地段 / 免费停车 / 零佣金",
  "Premium Facilities | huge balcony | HOT PRICE": "顶级设施 | 大阳台 | 超值价格",
  "Prime Location | Modern Layout | Al Reem Island": "黄金地段 | 现代布局 | Al Reem Island",
  "Prime Location | Modern Layout | Well Maintained": "黄金地段 | 现代布局 | 维护良好",
  "Prime Location || Tawtheeq Available || Direct Owner ||": "黄金地段 | 已备案 | 业主直租",
  "Prime Location| Spacious 1Br | Ready Unit": "黄金地段 | 宽敞 1居 | 现房",
  "Prime location 1bhk/ open kitchen /gym/pool/parking": "黄金地段 1居 / 开放式厨房 / 健身房 / 泳池 / 车位",
  "Pvt. terrace | Modern spacious 1/BHK | new kitchen | Free WiFi | Parking": "私人露台 | 现代宽敞 1居 | 新厨房 | 免费 WiFi | 带车位",
  "Pvt.terrace | Modern spacious 1/BHK | new kitchen | Free WiFi | Parking": "私人露台 | 现代宽敞 1居 | 新厨房 | 免费 WiFi | 带车位",
  "Ready To Move lSpacious Layout | Flexible Payments": "即可入住 l 宽敞布局 | 灵活付款",
  "Ready To Move | Refined Living | | Book Today": "即可入住 | 精致生活 | 今日预订",
  "Ready to Move | Luxury View | Don’t Miss Out": "即可入住 | 奢华景观 | 切勿错过",
  "Ready to move in ~ Stunning Facilities": "即可入住 ~ 顶级设施",
  "Ready to move || Prime location || Tawtheeq available": "即可入住 | 黄金地段 | 已备案",
  "Recently Vacated | Modern Urban Living | Book Now": "近期空置 | 现代都市生活 | 立即预订",
  "SPACIOUS 1BR - KITCHEN APPLIANCESS- PRIME LOCATION": "宽敞 1居 - 带厨房电器 - 黄金地段",
  "STUNNING 1 BHK+DINNING AREA, POOL, GYM & CAR PARK": "迷人 1居 + 餐厅区域 泳池、健身房 & 车位",
  "STUNNING VIEW 1 BHK w/ BALCONY and HIGHER FLOOR": "迷人景观 1居 带阳台 高层",
  "Sea & City View | Spacious Layout | Vacant": "海景 & 城市景 | 宽敞布局 | 空置",
  "Sea View Fully Furnished in Al Reem/ 5000 Monthly": "海景房 家具齐全 位于 Al Reem / 每月 5000",
  "Sea View Fully Furnished in Al Reem/5000 Monthly": "海景房 家具齐全 位于 Al Reem / 每月 5000",
  "Sea View l Hot Deal l flexible payment": "海景 l 超值房源 l 灵活付款",
  "Sea View | Furnished Studio | Vacant": "海景 | 带家具开间 | 空置",
  "Sea View | Ready To Move In | Vibrant Living": "海景 | 即可入住 | 活力生活",
  "Seaview Marina Bay by DAMAC 1 BR": "海景 Marina Bay by DAMAC 1居",
  "Separate Entrance 0 Commission Tawtheeq Free Bills": "独立入口 零佣金 已备案 含水电",
  "Serene Views | Well-Maintained | Ready to Move": "静谧景观 | 维护良好 | 即可入住",
  "Sigma Tower-Modern Studio Apartment-Al reem Island": "Sigma Tower - 现代开间公寓 - Al Reem Island",
  "Spacious 1 BR | Marina View | Balcony | Best Price": "宽敞 1居 | Marina 景观 | 带阳台 | 最佳价格",
  "Spacious 1 Bedroom Hall Apartment with Premium Facilities": "宽敞 1居带客厅公寓 顶级配套",
  "Spacious 1BHK | 2 Washroom | Central AC | basement Parking | Available for rent": "宽敞 1居 | 2卫 | 中央空调 | 地下停车位 | 可出租",
  "Spacious 1BHK| Higher floor| Balcony| Vacant": "宽敞 1居 | 高层 | 带阳台 | 空置",
  "Spacious 1BR | Modern Luxury Living | Ready to Move": "宽敞 1居 | 现代奢华生活 | 即可入住",
  "Spacious 1BR |Modern Luxury Living |Ready to Move": "宽敞 1居 | 现代奢华生活 | 即可入住",
  "Spacious 1BR| Huge Balcony | Vacant | Marina View": "宽敞 1居 | 大阳台 | 空置 | Marina 景观",
  "Spacious 1Bhk | Vacant | Upto 4 Payments": "宽敞 1居 | 空置 | 最多4期付款",
  "Spacious Full Community View | 1BR with balcony": "宽敞全社区景观 | 1居带阳台",
  "Spacious Studio || Prime Location || 0%commission || Tawtheeq Available||": "宽敞开间 | 黄金地段 | 零佣金 | 已备案",
  "Spacious Studio| 3 Payments | Prime Area": "宽敞开间 | 3期付款 | 黄金地段",
  "Spacious Unit ⁂ Prime Community ⁂ Elite Lifestyle": "宽敞户型 ⁂ 优质社区 ⁂ 精英生活方式",
  "Spacious studio II No commission II bills included": "宽敞开间 II 零佣金 II 含水电",
  "Specious 1 BHK with 2 Bath Close to All Facilities": "宽敞 1居 带2卫 临近所有配套",
  "Studio with Balcony with Storage Room | Amazing Sea View": "开间带阳台带储藏室 | 迷人海景",
  "Stunning !! 01bhk with balcony at prime location": "迷人！！1居带阳台 黄金地段",
  "Stunning View 1BR | Balcony | Great Deal": "迷人景观 1居 | 带阳台 | 超值",
  "Suite Furnished Room | Al Reem Island | Wave tower": "带家具套房 | Al Reem Island | Wave tower",
  "Suite Furnished Rooms | Al Reem Island | Wave tower | 5,000 AED Monthly": "带家具套房 | Al Reem Island | Wave tower | 每月 5,000 AED",
  "Sunlit One-Bedroom || 0% Commission || Tawtheeq Available": "阳光 1居 | 零佣金 | 已备案",
  "Sunlit One-Bedroom|Direct Owner|Tawtheeq Available": "阳光 1居 | 业主直租 | 已备案",
  "Tawtheeq|Furnished|1-BHK|Sep Kitchen|Pool|Balcony.": "已备案 | 带家具 | 1居 | 独立厨房 | 泳池 | 阳台",
  "Type C | Vacant in 10 Days | Spacious | Great View": "C户型 | 10天内空置 | 宽敞 | 极佳景观",
  "UPCOMNG HOT- Huge Size -Kitchen Appliances-Parking": "即将上市热门 - 超大面积 - 带厨房电器 - 带车位",
  "Unit Tawtheq|Duplex 1BR|Pvt Balcony|Share Pool+GYM": "已备案 | 复式 1居 | 私人阳台 | 公用泳池 + 健身房",
  "Upcoming Private Entrance Studio || Brand New || Direct Owner": "即将上市 私人入口开间 | 全新 | 业主直租",
  "Upcoming unique Apartment || Tawtheeq available | | Direct Owner": "即将上市 独特公寓 | 已备案 | 业主直租",
  "Upgraded 1 Bedroom Apt | Balcony | Amenities | Parking": "升级 1居公寓 | 带阳台 | 配套齐全 | 带车位",
  "VACANT SOON  /     TYPE D      /   WELL MAINTAINED": "即将空置 / D户型 / 维护良好",
  "VACANT SOON /    WELL MAINTAINED  /     GOOD PRICE": "即将空置 / 维护良好 / 优惠价格",
  "VACANT TYPE A 1BR APT W/RETAIL VIEW READY TO MOVE": "空置 A户型 1居公寓 临街景观 即可入住",
  "VACANT | 1BR + Storage Room | Furnished Unit": "空置 | 1居 + 储藏室 | 带家具户型",
  "VACANT | 2 Payments | Urban View": "空置 | 2期付款 | 都市景观",
  "VACANT- TYPE A- 1 BED APARTMENT- 72000 ONLY": "空置 - A户型 - 1居公寓 - 仅 72000",
  "Vacant I Spacious 1-BED | Prime Location": "空置 I 宽敞 1居 | 黄金地段",
  "Vacant On May | Spacious Layout | Great Community": "5月空置 | 宽敞布局 | 优质社区",
  "Vacant Unit | High Floor | Sea View |Spacious": "空置户型 | 高层 | 海景 | 宽敞",
  "Vacant Unit | Spacious Layout | Contact Asap |": "空置户型 | 宽敞布局 | 即刻联系",
  "Vacant | Book Now | Hot Deal | 4 Payments": "空置 | 立即预订 | 超值房源 | 4期付款",
  "Vacant |Spacious Layout | Prime Location": "空置 | 宽敞布局 | 黄金地段",
  "Vacant|Stunning 1BR|Modern Layout|Balcony Views": "空置 | 迷人 1居 | 现代布局 | 阳台景观",
  "Well-Kept 1BR | Prime Community | Move-in Ready": "维护良好 1居 | 优质社区 | 即可入住",
  "Zero Commission | Cozy 1BHK | Free Bills": "零佣金 | 温馨 1居 | 免账单",
  "prime Location Spacious 1Bhk Available for Rent": "黄金地段 宽敞 1居 可出租",
  "private entrance studio || Direct owner || Tawtheeq available ||": "私人入口开间 | 业主直租 | 已备案",
  "| Good Deal |  Ready to Move | Prime Location |": "| 超值 | 即可入住 | 黄金地段 |",
  "√ Move-in Ready | Fully Furnished | Mangrove View√": "√ 即可入住 | 家具齐全 | 红树林景观 √",
};

// ─── Source Title Paths ─────────────────────────────────────

const COLLECTIONS_CONFIG = [
  { collection: 'propertyfinder_raw', titlePath: 'property.title' },
  { collection: 'bayut_raw', titlePath: 'title' },
  { collection: 'dubizzle_raw', titlePath: 'name.en' },
  { collection: 'targeted_results', titlePath: 'title' },
];

function getPath(obj, path) {
  return path.split('.').reduce((o, k) => o?.[k], obj);
}

async function main() {
  const client = new MongoClient(config.mongo.uri, { maxPoolSize: 5 });
  await client.connect();
  const db = client.db(config.mongo.dbName);
  logger.info({ translations: Object.keys(TRANSLATIONS).length }, 'Translation map loaded');

  let totalUpdated = 0;
  let totalMissing = 0;

  for (const cfg of COLLECTIONS_CONFIG) {
    const col = db.collection(cfg.collection);
    const docs = await col.find({}, { projection: { _id: 1, [cfg.titlePath]: 1 } }).toArray();

    logger.info({ collection: cfg.collection, docs: docs.length }, 'Processing collection');

    const bulkOps = [];
    const missing = new Set();

    for (const doc of docs) {
      const title = getPath(doc, cfg.titlePath) || '';
      const zh = TRANSLATIONS[title];
      if (zh) {
        bulkOps.push({
          updateOne: {
            filter: { _id: doc._id },
            update: { $set: { title_zh: zh } },
          },
        });
      } else if (title) {
        missing.add(title);
        // Still write the original as fallback
        bulkOps.push({
          updateOne: {
            filter: { _id: doc._id },
            update: { $set: { title_zh: title } },
          },
        });
      }
    }

    if (bulkOps.length > 0) {
      const result = await col.bulkWrite(bulkOps, { ordered: false });
      const updated = result.modifiedCount + result.upsertedCount;
      totalUpdated += updated;
      logger.info({ collection: cfg.collection, updated, missing: missing.size }, 'Updated');
    }

    if (missing.size > 0) {
      totalMissing += missing.size;
      logger.warn({ collection: cfg.collection, samples: [...missing].slice(0, 3) }, 'Missing translations (kept English)');
    }
  }

  logger.info({ totalUpdated, totalMissing }, 'Translation complete');
  await client.close();
}

main().catch((err) => {
  logger.fatal({ err: err.message }, 'Translation script failed');
  process.exit(1);
});
